#!/usr/bin/env bash
#
# Test KV cache quantization quality by comparing perplexity across cache types.
# Downloads a small model and wikitext dataset if not already present.
#
# Usage:
#   tests/test-kv-cache-quantization-perp.sh [options] [build_dir]
#
# Options:
#   -c <tiny|tiny2|small|mid|large>  Size config preset (repeatable, default: small)
#   --mixed-only                     Skip same-type tests, only run mixed K/V
#   --csv <file>                     Write results to specific CSV file (auto-generated by default)
#
# Config presets (n_chunks / n_ctx sweep):
#   tiny   — 1 chunk,  n_ctx 64               (single quick check, no stdev)
#   tiny2  — 1 chunk,  n_ctx 64,72            (smoke test with stdev)
#   small  — 2 chunks, n_ctx 64,128           (quick, 2 context sizes)
#   mid    — 4 chunks, n_ctx 448,512          (balanced, near standard 512)
#   large  — 8 chunks, n_ctx 448,512,1024,1536,2048  (thorough, 5 context sizes)
#
# WARNING: Presets smaller than 'mid' (tiny, tiny2, small) are prone to statistical noise.
# At very small context sizes, quantization error can occasionally result in lower PPL
# than f16 due to numerical artifacts or the "noise" acting as accidental regularization.
# Use 'mid' or 'large' for reliable quality comparisons.
#
# Perplexity is deterministic — repeating the same run gives identical PPL.
# Instead, presets sweep multiple n_ctx values to measure quality stability
# across context lengths. Mean/stdev are computed across the n_ctx sweep.
#
# Environment variables:
#   MODEL_DIR    — directory for model files (default: models)
#   MODEL_NAME   — GGUF filename
#   MODEL_URL    — download URL
#   CSV          — set to 0 to disable auto CSV output (default: 1)
#   MAX_PPL_REGRESSION_PCT — max allowed PPL regression vs f16 (default: 21)
#
# Examples:
#   tests/test-kv-cache-quantization-perp.sh -c small -c mid --csv ppl.csv
#   tests/test-kv-cache-quantization-perp.sh -c large --csv ppl.csv build
#
set -euo pipefail

# --- Parse arguments ---

CONFIGS=()
CSV_FILE=""
BUILD_DIR=""
MIXED_ONLY=false

while [ $# -gt 0 ]; do
    case "$1" in
        -c)
            shift
            CONFIGS+=("$1")
            shift
            ;;
        --csv)
            shift
            CSV_FILE="$1"
            shift
            ;;
        --mixed-only)
            MIXED_ONLY=true
            shift
            ;;
        -h|--help)
            head -35 "$0" | tail -34
            exit 0
            ;;
        *)
            BUILD_DIR="$1"
            shift
            ;;
    esac
done

BUILD_DIR="${BUILD_DIR:-build}"
PERPLEXITY="$BUILD_DIR/bin/llama-perplexity"

MODEL_DIR="${MODEL_DIR:-models}"
MODEL_NAME="${MODEL_NAME:-Mistral-7B-Instruct-v0.3-Q4_K_S.gguf}"
MODEL_URL="${MODEL_URL:-https://huggingface.co/bartowski/Mistral-7B-Instruct-v0.3-GGUF/resolve/main/Mistral-7B-Instruct-v0.3-Q4_K_S.gguf}"
MODEL_PATH="$MODEL_DIR/$MODEL_NAME"

# When no -c is given, default to small
if [ ${#CONFIGS[@]} -eq 0 ]; then
    CONFIGS=("tiny2")
fi


DATASET_DIR="wikitext-2-raw"
DATASET_FILE="$DATASET_DIR/wiki.test.raw"
DATASET_ZIP="wikitext-2-raw-v1.zip"
DATASET_URL="https://huggingface.co/datasets/ggml-org/ci/resolve/main/$DATASET_ZIP"

MAX_PPL_REGRESSION_PCT="${MAX_PPL_REGRESSION_PCT:-21}"

CACHE_TYPES=("tbq3_0" "q4_0" "pq3_0" "tbq4_0" "f16" "q8_0" "pq4_0")

MIXED_CACHE_TYPES=(
    "tbq3_0:pq3_0"
    "tbq4_0:pq4_0"
    "tbq3_0:q8_0"
    "tbq4_0:f16"
    "q8_0:pq3_0"
    "f16:pq4_0"
)

# --- Config presets ---

config_n_chunks() {
    case "$1" in
        tiny)  echo 1 ;;
        tiny2) echo 1 ;;
        small) echo 2 ;;
        mid)   echo 4 ;;
        large) echo 8 ;;
        *) echo "Error: unknown config '$1' (expected tiny, tiny2, small, mid, large)" >&2; exit 1 ;;
    esac
}

config_n_ctx_list() {
    case "$1" in
        tiny)  echo "64" ;;
        tiny2) echo "64 72" ;;
        small) echo "64 128" ;;
        mid)   echo "448 512" ;;
        large) echo "448 512 1024 1536 2048" ;;
        *) echo "Error: unknown config '$1'" >&2; exit 1 ;;
    esac
}

# --- Download dependencies ---

if [ ! -f "$PERPLEXITY" ]; then
    echo "Error: $PERPLEXITY not found. Build the project first."
    echo "  cmake -B $BUILD_DIR && cmake --build $BUILD_DIR -j\$(nproc)"
    exit 1
fi

mkdir -p "$MODEL_DIR"

if [ ! -f "$MODEL_PATH" ] || [ "$(stat -c%s "$MODEL_PATH" 2>/dev/null || echo 0)" -lt 1000000 ]; then
    [ -f "$MODEL_PATH" ] && rm -f "$MODEL_PATH"
    echo "Downloading model: $MODEL_NAME ..."
    if command -v curl &> /dev/null; then
        curl -L --fail -C - -o "$MODEL_PATH" "$MODEL_URL"
    elif command -v wget &> /dev/null; then
        wget -O "$MODEL_PATH" "$MODEL_URL"
    else
        echo "Error: neither curl nor wget found"
        exit 1
    fi

    FILE_SIZE=$(stat -c%s "$MODEL_PATH" 2>/dev/null || echo 0)
    if [ "$FILE_SIZE" -lt 1000000 ]; then
        echo "Error: downloaded file is only $FILE_SIZE bytes — likely a redirect or error page."
        echo "Download the model manually:"
        echo "  curl -L --fail -o $MODEL_PATH $MODEL_URL"
        rm -f "$MODEL_PATH"
        exit 1
    fi
    echo "Model downloaded to $MODEL_PATH ($((FILE_SIZE / 1048576)) MB)"
else
    echo "Model already exists: $MODEL_PATH"
fi

if [ ! -f "$DATASET_FILE" ]; then
    echo "Downloading wikitext-2 dataset..."
    if command -v curl &> /dev/null; then
        curl -L -o "$DATASET_ZIP" "$DATASET_URL"
    elif command -v wget &> /dev/null; then
        wget -O "$DATASET_ZIP" "$DATASET_URL"
    else
        echo "Error: neither curl nor wget found"
        exit 1
    fi
    unzip -o "$DATASET_ZIP"
    rm -f "$DATASET_ZIP"
    echo "Dataset extracted to $DATASET_DIR"
else
    echo "Dataset already exists: $DATASET_FILE"
fi

# --- GPU device detection ---

detect_gpu_device() {
    local gpu_info=""
    local bench_bin="$BUILD_DIR/bin/llama-bench"

    if [ -f "$bench_bin" ]; then
        gpu_info=$("$bench_bin" --list-devices 2>&1 | grep -E '^\s+(Vulkan|CUDA|Metal|SYCL|ROCm)' | head -1 | sed 's/^[[:space:]]*//' || true)
    fi

    if [ -z "$gpu_info" ]; then
        if command -v nvidia-smi &> /dev/null; then
            gpu_info=$(nvidia-smi --query-gpu=name --format=csv,noheader 2>/dev/null | head -1 || true)
        elif command -v vulkaninfo &> /dev/null; then
            gpu_info=$(vulkaninfo 2>/dev/null | grep "deviceName" | head -1 | sed 's/.*= //' || true)
        fi
    fi

    echo "${gpu_info:-unknown}"
}

GPU_DEVICE=$(detect_gpu_device)

# Auto-generate CSV filename unless explicitly provided or disabled (CSV=0)
CSV_FINAL=""
if [ -z "$CSV_FILE" ] && [ "${CSV:-1}" != "0" ]; then
    sanitize() { echo "$1" | tr '[:upper:]' '[:lower:]' | sed 's/[^a-z0-9._-]/_/g; s/__*/_/g; s/^_//; s/_$//'; }
    GPU_SHORT=$(echo "$GPU_DEVICE" | sed 's/^[A-Za-z]*[0-9]*: //; s/ ([0-9].*//')
    GPU_TAG=$(sanitize "$GPU_SHORT")
    MODEL_TAG=$(sanitize "${MODEL_NAME%.gguf}")
    CFG_TAG=$(printf '%s-' "${CONFIGS[@]}" | sed 's/-$//')
    CSV_FILE="kv-perp_${GPU_TAG}_${MODEL_TAG}_${CFG_TAG}_$(date +%Y%m%d_%H%M%S).csv"
fi
if [ -n "$CSV_FILE" ]; then
    CSV_FINAL="$CSV_FILE"
    CSV_FILE=$(mktemp /tmp/kv-perp-XXXXXX.csv)
fi

# --- Log file setup (same name as CSV, .txt extension) ---

LOG_FILE=""
if [ -n "$CSV_FINAL" ]; then
    LOG_FILE="${CSV_FINAL%.csv}.txt"
    exec > >(tee -a "$LOG_FILE") 2>&1
fi

# --- Bits per value (theoretical) ---

get_bpw() {
    case "$1" in
        f16)     echo "16.00" ;;
        q8_0)    echo "8.50"  ;;
        q4_0)    echo "4.50"  ;;
        q4_1)    echo "5.00"  ;;
        q5_0)    echo "5.50"  ;;
        q5_1)    echo "6.00"  ;;
        q2_K)    echo "2.625" ;;
        q3_K)    echo "3.44"  ;;
        q4_K)    echo "4.50"  ;;
        q5_K)    echo "5.50"  ;;
        q6_K)    echo "6.56"  ;;
        iq2_xxs) echo "2.06"  ;;
        iq2_xs)  echo "2.31"  ;;
        iq2_s)   echo "2.50"  ;;
        iq3_xxs) echo "3.06"  ;;
        iq3_s)   echo "3.44"  ;;
        pq3_0)   echo "3.25"  ;;
        pq4_0)   echo "4.25"  ;;
        tbq3_0)  echo "4.25"  ;;
        tbq4_0)  echo "5.25"  ;;
        *)       echo "0.00"  ;;
    esac
}

# --- Perplexity extraction ---

extract_ppl() {
    local output="$1"
    echo "$output" | grep -oP 'PPL = \K[0-9]+\.[0-9]+' | tail -1
}

# --- CSV setup ---

CSV_ROWS=()

csv_init() {
    if [ -n "$CSV_FILE" ]; then
        echo "gpu_device,model,config,cache_k,cache_v,mixed,norm_correction,bpw_avg,n_chunks,n_ctx_sweep,ppl_mean,ppl_stdev,time_mean_s,time_stdev_s,ppl_vs_f16_pct,ppl_vs_f16_pct_stdev,time_vs_f16_x,time_vs_f16_x_stdev,prbs,prbs_stdev" > "$CSV_FILE"
    fi
}

NC_FLAG="off"

csv_append() {
    local k_type="$1" v_type="$2" is_mixed="$3" n_chunks="$4" n_ctx_sweep="$5"
    local ppl_mean="$6" ppl_sd="$7" time_mean="$8" time_sd="$9"
    local ppl_vs_f16="${10}" ppl_vs_f16_sd="${11}" time_vs_f16="${12}" time_vs_f16_sd="${13}" config_name="${14}"
    local baseline_ppl_csv="${15}"
    local bpw_k=$(get_bpw "$k_type")
    local bpw_v=$(get_bpw "$v_type")
    local bpw_avg=$(echo "$bpw_k $bpw_v" | awk '{printf "%.2f", ($1 + $2) / 2}')
    local prbs_val="" prbs_sd_val=""
    if [ -n "$baseline_ppl_csv" ] && [ "$bpw_avg" != "16.00" ]; then
        prbs_val=$(echo "$ppl_mean $baseline_ppl_csv $bpw_avg" | awk '{
            bs = 16 - $3; if (bs > 0) printf "%.4f", ($1 - $2) / bs; else print ""
        }')
        prbs_sd_val=$(echo "$ppl_sd $bpw_avg" | awk '{
            bs = 16 - $2; if (bs > 0) printf "%.4f", $1 / bs; else print ""
        }')
    fi
    local row="\"$GPU_DEVICE\",\"$MODEL_NAME\",\"$config_name\",\"$k_type\",\"$v_type\",\"$is_mixed\",\"$NC_FLAG\",$bpw_avg,$n_chunks,\"$n_ctx_sweep\",$ppl_mean,$ppl_sd,$time_mean,$time_sd,$ppl_vs_f16,$ppl_vs_f16_sd,$time_vs_f16,$time_vs_f16_sd,$prbs_val,$prbs_sd_val"
    CSV_ROWS+=("$row")
    if [ -n "$CSV_FILE" ]; then
        echo "$row" >> "$CSV_FILE"
    fi
}

csv_init

# --- Print header ---

echo ""
echo "=========================================="
echo " KV Cache Quantization Perplexity Test"
echo "=========================================="
echo " GPU:      $GPU_DEVICE"
echo " Model:    $MODEL_NAME"
echo " Dataset:  $DATASET_FILE"
echo " Configs:  ${CONFIGS[*]}"
for cfg_info in "${CONFIGS[@]}"; do
    local_chunks=$(config_n_chunks "$cfg_info")
    local_ctx_list=$(config_n_ctx_list "$cfg_info")
    echo "   $cfg_info: chunks=$local_chunks n_ctx=[$local_ctx_list]"
done
echo " α-scale:  on (TBQ/PQ types compared with MSE-optimal norm correction)"
if [ -n "$CSV_FINAL" ]; then
    echo " CSV:      $CSV_FINAL"
    echo " Log:      $LOG_FILE"
fi
echo "=========================================="
echo ""

# --- Helper: run perplexity once ---

run_perplexity_once() {
    local k_type="$1" v_type="$2" n_ctx="$3" n_chunks="$4"

    local start_time end_time elapsed_ms elapsed_s output ppl

    start_time=$(date +%s%N)

    output=$("$PERPLEXITY" \
        -m "$MODEL_PATH" \
        -f "$DATASET_FILE" \
        --cache-type-k "$k_type" \
        --cache-type-v "$v_type" \
        -n "$n_ctx" \
        --chunks "$n_chunks" \
        2>&1) || {
        echo "FAILED" >&2
        echo "$output" | tail -10 >&2
        return 1
    }

    end_time=$(date +%s%N)
    elapsed_ms=$(( (end_time - start_time) / 1000000 ))
    elapsed_s=$(echo "$elapsed_ms" | awk '{printf "%.2f", $1/1000}')

    ppl=$(extract_ppl "$output")
    if [ -z "$ppl" ]; then
        echo "PARSE_FAILED" >&2
        echo "$output" | tail -10 >&2
        return 1
    fi

    echo "$ppl $elapsed_s"
}

# --- Helper: run across n_ctx values, compute mean and stdev ---

run_perplexity_sweep() {
    local k_type="$1" v_type="$2" n_chunks="$3"
    shift 3
    local ctx_list=("$@")
    local n_runs=${#ctx_list[@]}

    local ppls=() times=()

    for (( i=0; i<n_runs; i++ )); do
        local ctx="${ctx_list[$i]}"
        local result
        result=$(run_perplexity_once "$k_type" "$v_type" "$ctx" "$n_chunks") || return 1
        local ppl_val time_val
        ppl_val=$(echo "$result" | awk '{print $1}')
        time_val=$(echo "$result" | awk '{print $2}')
        ppls+=("$ppl_val")
        times+=("$time_val")
        if [ "$n_runs" -gt 1 ]; then
            echo "    n_ctx=$ctx: PPL=$ppl_val (${time_val}s)" >&2
        fi
    done

    local ppl_mean ppl_stdev time_mean time_stdev
    if [ "$n_runs" -eq 1 ]; then
        ppl_mean="${ppls[0]}"
        ppl_stdev="0.00"
        time_mean="${times[0]}"
        time_stdev="0.00"
    else
        ppl_mean=$(printf '%s\n' "${ppls[@]}" | awk '{s+=$1; n++} END {printf "%.4f", s/n}')
        ppl_stdev=$(printf '%s\n' "${ppls[@]}" | awk -v mean="$ppl_mean" '{d=$1-mean; ss+=d*d; n++} END {printf "%.4f", sqrt(ss/(n-1))}')
        time_mean=$(printf '%s\n' "${times[@]}" | awk '{s+=$1; n++} END {printf "%.2f", s/n}')
        time_stdev=$(printf '%s\n' "${times[@]}" | awk -v mean="$time_mean" '{d=$1-mean; ss+=d*d; n++} END {printf "%.2f", sqrt(ss/(n-1))}')
    fi

    echo "$ppl_mean $ppl_stdev $time_mean $time_stdev"
}

# --- Main benchmark loop over configs ---

num_failed=0

# TBQ/PQ types that are affected by norm correction
is_tq_type() {
    case "$1" in
        tbq3_0|tbq4_0|pq3_0|pq4_0) return 0 ;;
        *) return 1 ;;
    esac
}

for cfg in "${CONFIGS[@]}"; do
    N_CHUNKS_CFG=$(config_n_chunks "$cfg")
    read -r -a N_CTX_LIST <<< "$(config_n_ctx_list "$cfg")"
    N_RUNS=${#N_CTX_LIST[@]}
    HAS_STDEV=$(( N_RUNS > 1 ))

    echo ""
    echo "############################################"
    echo " Config: $cfg  (chunks=$N_CHUNKS_CFG, n_ctx=[${N_CTX_LIST[*]}])"
    echo "############################################"
    echo ""

    declare -A ppl_results ppl_sd_results time_results time_sd_results
    declare -A ppl_results_a ppl_sd_results_a time_results_a time_sd_results_a

    # --- Helper: format value±sd (only shows ± when HAS_STDEV) ---
    fmt_pm() { [ "$HAS_STDEV" -eq 1 ] && echo "${1}±${2}" || echo "$1"; }

    # --- Helper: compute regression% ± propagated stdev ---
    # regression = ((ppl - base) / base) * 100
    # sd_regression = (ppl_sd / base) * 100  (base treated as constant per run)
    fmt_regression() {
        local ppl="$1" ppl_sd="$2" base="$3"
        local reg reg_sd
        reg=$(echo "$ppl $base" | awk '{printf "%.2f", (($1 - $2) / $2) * 100}')
        if [ "$HAS_STDEV" -eq 1 ]; then
            reg_sd=$(echo "$ppl_sd $base" | awk '{printf "%.2f", ($1 / $2) * 100}')
            printf "%+.2f±%s%%" "$reg" "$reg_sd"
        else
            printf "%+.2f%%" "$reg"
        fi
    }

    # --- Helper: compute speedup ratio ± propagated stdev ---
    # ratio = t / base_t
    # sd_ratio = sqrt((sd_t/base_t)^2 + (t*sd_base_t/base_t^2)^2)
    fmt_slowdown() {
        local t="$1" t_sd="$2" base_t="$3" base_t_sd="$4"
        local ratio ratio_sd
        ratio=$(echo "$t $base_t" | awk '{if ($2 > 0) printf "%.1f", $1/$2; else {print "n/a"; exit}}')
        if [ "$HAS_STDEV" -eq 1 ]; then
            ratio_sd=$(echo "$t $t_sd $base_t $base_t_sd" | awk '{
                if ($3 > 0) {
                    a = ($2/$3)^2; b = ($1*$4/($3*$3))^2;
                    printf "%.1f", sqrt(a+b)
                } else print "0.0"
            }')
            echo "${ratio}±${ratio_sd}x"
        else
            echo "${ratio}x"
        fi
    }

    # --- Helper: compute PRBS (PPL Regression per Bit Saved) ± propagated stdev ---
    # PRBS = (PPL_quant - PPL_f16) / (16 - BPW_avg)
    # Lower is better: cost in perplexity per bit of memory saved vs f16.
    # sd_prbs = ppl_sd / (16 - BPW_avg)
    fmt_prbs() {
        local ppl="$1" ppl_sd="$2" base="$3" bpw="$4"
        local prbs prbs_sd
        prbs=$(echo "$ppl $base $bpw" | awk '{
            bits_saved = 16 - $3;
            if (bits_saved > 0) printf "%.4f", ($1 - $2) / bits_saved;
            else print "n/a"
        }')
        if [ "$HAS_STDEV" -eq 1 ]; then
            prbs_sd=$(echo "$ppl_sd $bpw" | awk '{
                bits_saved = 16 - $2;
                if (bits_saved > 0) printf "%.4f", $1 / bits_saved;
                else print "0.0000"
            }')
            echo "${prbs}±${prbs_sd}"
        else
            echo "$prbs"
        fi
    }

    # raw PRBS value for CSV
    calc_prbs() {
        local ppl="$1" base="$2" bpw="$3"
        echo "$ppl $base $bpw" | awk '{
            bits_saved = 16 - $3;
            if (bits_saved > 0) printf "%.4f", ($1 - $2) / bits_saved;
            else print ""
        }'
    }
    calc_prbs_sd() {
        local ppl_sd="$1" bpw="$2"
        echo "$ppl_sd $bpw" | awk '{
            bits_saved = 16 - $2;
            if (bits_saved > 0) printf "%.4f", $1 / bits_saved;
            else print ""
        }'
    }

    # --- Baseline ---

    run_baseline() {
        echo "--- Running f16 baseline [$cfg] ---"
        local result
        result=$(run_perplexity_sweep "f16" "f16" "$N_CHUNKS_CFG" "${N_CTX_LIST[@]}") || {
            echo "FAILED: perplexity run crashed for f16 baseline"
            exit 1
        }
        ppl_results["f16"]=$(echo "$result" | awk '{print $1}')
        ppl_sd_results["f16"]=$(echo "$result" | awk '{print $2}')
        time_results["f16"]=$(echo "$result" | awk '{print $3}')
        time_sd_results["f16"]=$(echo "$result" | awk '{print $4}')
        echo "  f16 PPL = $(fmt_pm "${ppl_results[f16]}" "${ppl_sd_results[f16]}")  ($(fmt_pm "${time_results[f16]}" "${time_sd_results[f16]}")s)"
        echo ""
    }

    if [ "$MIXED_ONLY" = true ]; then
        run_baseline
    else

    export GGML_TQ_NORM_CORRECTION=0
    for cache_type in "${CACHE_TYPES[@]}"; do
        bpw=$(get_bpw "$cache_type")
        echo "--- Running perplexity with K=$cache_type V=$cache_type [$cfg] (BPW=$bpw) ---"

        result=$(run_perplexity_sweep "$cache_type" "$cache_type" "$N_CHUNKS_CFG" "${N_CTX_LIST[@]}") || {
            echo "FAILED: perplexity run crashed for cache type $cache_type"
            exit 1
        }

        ppl_results["$cache_type"]=$(echo "$result" | awk '{print $1}')
        ppl_sd_results["$cache_type"]=$(echo "$result" | awk '{print $2}')
        time_results["$cache_type"]=$(echo "$result" | awk '{print $3}')
        time_sd_results["$cache_type"]=$(echo "$result" | awk '{print $4}')
        echo "  $cache_type PPL = $(fmt_pm "${ppl_results[$cache_type]}" "${ppl_sd_results[$cache_type]}")  ($(fmt_pm "${time_results[$cache_type]}" "${time_sd_results[$cache_type]}")s)"
        echo ""

        if is_tq_type "$cache_type"; then
            echo "--- Running perplexity with K=$cache_type V=$cache_type [$cfg] (α, BPW=$bpw) ---"
            export GGML_TQ_NORM_CORRECTION=1
            result=$(run_perplexity_sweep "$cache_type" "$cache_type" "$N_CHUNKS_CFG" "${N_CTX_LIST[@]}") || {
                echo "FAILED: perplexity run crashed for cache type $cache_type (α)"
                exit 1
            }
            export GGML_TQ_NORM_CORRECTION=0
            ppl_results_a["$cache_type"]=$(echo "$result" | awk '{print $1}')
            ppl_sd_results_a["$cache_type"]=$(echo "$result" | awk '{print $2}')
            time_results_a["$cache_type"]=$(echo "$result" | awk '{print $3}')
            time_sd_results_a["$cache_type"]=$(echo "$result" | awk '{print $4}')
            echo "  $cache_type (α) PPL = $(fmt_pm "${ppl_results_a[$cache_type]}" "${ppl_sd_results_a[$cache_type]}")  ($(fmt_pm "${time_results_a[$cache_type]}" "${time_sd_results_a[$cache_type]}")s)"
            echo ""
        fi
    done

    # --- Print same-type summary ---

    echo ""
    echo "=========================================="
    echo " Results Summary [$cfg]"
    echo "=========================================="
    if [ "$HAS_STDEV" -eq 1 ]; then
        printf "  %-14s %-6s %16s %18s %14s %16s\n" "Type" "BPW" "PPL (mean±sd)" "vs f16" "PRBS" "Time"
    else
        printf "  %-14s %-6s %10s %12s %10s %10s\n" "Type" "BPW" "PPL" "vs f16" "PRBS" "Time"
    fi
    printf "  %-14s %-6s %16s %18s %14s %16s\n" "----" "---" "---" "------" "----" "----"

    baseline_ppl="${ppl_results[f16]}"
    baseline_ppl_sd="${ppl_sd_results[f16]}"
    baseline_time="${time_results[f16]}"
    baseline_time_sd="${time_sd_results[f16]}"

    for cache_type in "${CACHE_TYPES[@]}"; do
        ppl="${ppl_results[$cache_type]}"
        ppl_sd="${ppl_sd_results[$cache_type]}"
        elapsed="${time_results[$cache_type]}"
        elapsed_sd="${time_sd_results[$cache_type]}"
        bpw=$(get_bpw "$cache_type")

        ppl_disp=$(fmt_pm "$ppl" "$ppl_sd")
        time_disp="$(fmt_pm "$elapsed" "$elapsed_sd")s"

        if [ "$cache_type" = "f16" ]; then
            printf "  %-14s %-6s %16s %18s %14s %16s\n" "$cache_type" "$bpw" "$ppl_disp" "(baseline)" "-" "$time_disp"
        else
            reg_disp=$(fmt_regression "$ppl" "$ppl_sd" "$baseline_ppl")
            prbs_disp=$(fmt_prbs "$ppl" "$ppl_sd" "$baseline_ppl" "$bpw")
            slow_disp=$(fmt_slowdown "$elapsed" "$elapsed_sd" "$baseline_time" "$baseline_time_sd")
            printf "  %-14s %-6s %16s %18s %14s %12s (%s)\n" "$cache_type" "$bpw" "$ppl_disp" "$reg_disp" "$prbs_disp" "$time_disp" "$slow_disp"
        fi

        if [ -n "${ppl_results_a[$cache_type]:-}" ]; then
            ppl_a="${ppl_results_a[$cache_type]}"
            ppl_sd_a="${ppl_sd_results_a[$cache_type]}"
            elapsed_a="${time_results_a[$cache_type]}"
            elapsed_sd_a="${time_sd_results_a[$cache_type]}"
            ppl_disp_a=$(fmt_pm "$ppl_a" "$ppl_sd_a")
            time_disp_a="$(fmt_pm "$elapsed_a" "$elapsed_sd_a")s"
            reg_disp_a=$(fmt_regression "$ppl_a" "$ppl_sd_a" "$baseline_ppl")
            prbs_disp_a=$(fmt_prbs "$ppl_a" "$ppl_sd_a" "$baseline_ppl" "$bpw")
            slow_disp_a=$(fmt_slowdown "$elapsed_a" "$elapsed_sd_a" "$baseline_time" "$baseline_time_sd")
            printf "  %-14s %-6s %16s %18s %14s %12s (%s)\n" "  └ α" "-" "$ppl_disp_a" "$reg_disp_a" "$prbs_disp_a" "$time_disp_a" "$slow_disp_a"
        fi
    done

    echo "  --"
    echo "  PRBS = PPL Regression per Bit Saved = (PPL_quant - PPL_f16) / (16 - BPW)"
    echo "         Lower is better: perplexity cost per bit of memory saved vs f16."
    echo "  └ α  = MSE-optimal norm correction for TBQ/PQ types"

    echo "=========================================="

    fi # end !MIXED_ONLY

    baseline_ppl="${ppl_results[f16]}"
    baseline_ppl_sd="${ppl_sd_results[f16]}"
    baseline_time="${time_results[f16]}"
    baseline_time_sd="${time_sd_results[f16]}"

    # --- Mixed K/V cache type tests ---

    declare -A mixed_ppl_results mixed_ppl_sd_results mixed_time_results mixed_time_sd_results
    declare -A mixed_ppl_results_a mixed_ppl_sd_results_a mixed_time_results_a mixed_time_sd_results_a

    echo ""
    echo "=========================================="
    echo " Mixed K/V Cache Type Tests [$cfg]"
    echo "=========================================="
    echo ""

    export GGML_TQ_NORM_CORRECTION=0
    for mixed in "${MIXED_CACHE_TYPES[@]}"; do
        k_type="${mixed%%:*}"
        v_type="${mixed##*:}"
        
        bpw_k=$(get_bpw "$k_type")
        bpw_v=$(get_bpw "$v_type")
        bpw_avg=$(echo "$bpw_k $bpw_v" | awk '{printf "%.2f", ($1 + $2) / 2}')

        echo "--- Running perplexity with K=$k_type V=$v_type [$cfg] (BPW=$bpw_avg) ---"

        result=$(run_perplexity_sweep "$k_type" "$v_type" "$N_CHUNKS_CFG" "${N_CTX_LIST[@]}") || {
            echo "FAILED: perplexity run crashed for mixed cache K=$k_type V=$v_type"
            exit 1
        }

        mixed_ppl_results["$mixed"]=$(echo "$result" | awk '{print $1}')
        mixed_ppl_sd_results["$mixed"]=$(echo "$result" | awk '{print $2}')
        mixed_time_results["$mixed"]=$(echo "$result" | awk '{print $3}')
        mixed_time_sd_results["$mixed"]=$(echo "$result" | awk '{print $4}')
        echo "  K=$k_type V=$v_type PPL = $(fmt_pm "${mixed_ppl_results[$mixed]}" "${mixed_ppl_sd_results[$mixed]}")  ($(fmt_pm "${mixed_time_results[$mixed]}" "${mixed_time_sd_results[$mixed]}")s)"
        echo ""

        if is_tq_type "$k_type" || is_tq_type "$v_type"; then
            echo "--- Running perplexity with K=$k_type V=$v_type [$cfg] (α, BPW=$bpw_avg) ---"
            export GGML_TQ_NORM_CORRECTION=1
            result=$(run_perplexity_sweep "$k_type" "$v_type" "$N_CHUNKS_CFG" "${N_CTX_LIST[@]}") || {
                echo "FAILED: perplexity run crashed for mixed cache K=$k_type V=$v_type (α)"
                exit 1
            }
            export GGML_TQ_NORM_CORRECTION=0
            mixed_ppl_results_a["$mixed"]=$(echo "$result" | awk '{print $1}')
            mixed_ppl_sd_results_a["$mixed"]=$(echo "$result" | awk '{print $2}')
            mixed_time_results_a["$mixed"]=$(echo "$result" | awk '{print $3}')
            mixed_time_sd_results_a["$mixed"]=$(echo "$result" | awk '{print $4}')
            echo "  K=$k_type V=$v_type (α) PPL = $(fmt_pm "${mixed_ppl_results_a[$mixed]}" "${mixed_ppl_sd_results_a[$mixed]}")  ($(fmt_pm "${mixed_time_results_a[$mixed]}" "${mixed_time_sd_results_a[$mixed]}")s)"
            echo ""
        fi
    done

    echo ""
    echo "=========================================="
    echo " Mixed K/V Results Summary [$cfg]"
    echo "=========================================="
    if [ "$HAS_STDEV" -eq 1 ]; then
        printf "  %-12s %-12s %-6s %16s %18s %14s %16s\n" "K type" "V type" "BPW" "PPL (mean±sd)" "vs f16" "PRBS" "Time"
    else
        printf "  %-12s %-12s %-6s %10s %12s %10s %10s\n" "K type" "V type" "BPW" "PPL" "vs f16" "PRBS" "Time"
    fi
    printf "  %-12s %-12s %-6s %16s %18s %14s %16s\n" "------" "------" "---" "---" "------" "----" "----"

    for mixed in "${MIXED_CACHE_TYPES[@]}"; do
        k_type="${mixed%%:*}"
        v_type="${mixed##*:}"
        ppl="${mixed_ppl_results[$mixed]}"
        ppl_sd="${mixed_ppl_sd_results[$mixed]}"
        elapsed="${mixed_time_results[$mixed]}"
        elapsed_sd="${mixed_time_sd_results[$mixed]}"
        
        bpw_k=$(get_bpw "$k_type")
        bpw_v=$(get_bpw "$v_type")
        bpw_avg=$(echo "$bpw_k $bpw_v" | awk '{printf "%.2f", ($1 + $2) / 2}')

        ppl_disp=$(fmt_pm "$ppl" "$ppl_sd")
        time_disp="$(fmt_pm "$elapsed" "$elapsed_sd")s"
        reg_disp=$(fmt_regression "$ppl" "$ppl_sd" "$baseline_ppl")
        prbs_disp=$(fmt_prbs "$ppl" "$ppl_sd" "$baseline_ppl" "$bpw_avg")
        slow_disp=$(fmt_slowdown "$elapsed" "$elapsed_sd" "$baseline_time" "$baseline_time_sd")
        printf "  %-12s %-12s %-6s %16s %18s %14s %12s (%s)\n" "$k_type" "$v_type" "$bpw_avg" "$ppl_disp" "$reg_disp" "$prbs_disp" "$time_disp" "$slow_disp"

        if [ -n "${mixed_ppl_results_a[$mixed]:-}" ]; then
            ppl_a="${mixed_ppl_results_a[$mixed]}"
            ppl_sd_a="${mixed_ppl_sd_results_a[$mixed]}"
            elapsed_a="${mixed_time_results_a[$mixed]}"
            elapsed_sd_a="${mixed_time_sd_results_a[$mixed]}"
            ppl_disp_a=$(fmt_pm "$ppl_a" "$ppl_sd_a")
            time_disp_a="$(fmt_pm "$elapsed_a" "$elapsed_sd_a")s"
            reg_disp_a=$(fmt_regression "$ppl_a" "$ppl_sd_a" "$baseline_ppl")
            prbs_disp_a=$(fmt_prbs "$ppl_a" "$ppl_sd_a" "$baseline_ppl" "$bpw_avg")
            slow_disp_a=$(fmt_slowdown "$elapsed_a" "$elapsed_sd_a" "$baseline_time" "$baseline_time_sd")
            printf "  %-12s %-12s %-6s %16s %18s %14s %12s (%s)\n" "  └ α" "" "-" "$ppl_disp_a" "$reg_disp_a" "$prbs_disp_a" "$time_disp_a" "$slow_disp_a"
        fi
    done

    echo "  --"
    echo "  PRBS = PPL Regression per Bit Saved = (PPL_quant - PPL_f16) / (16 - BPW)"
    echo "         Lower is better: perplexity cost per bit of memory saved vs f16."
    echo "  BPW  = average of K and V bits-per-value for mixed types"
    echo "  └ α  = MSE-optimal norm correction for TBQ/PQ types"

    echo "=========================================="

    # --- Check regressions ---

    if [ "$MIXED_ONLY" = false ]; then
    for cache_type in "${CACHE_TYPES[@]}"; do
        [ "$cache_type" = "f16" ] && continue

        ppl="${ppl_results[$cache_type]}"
        exceeded=$(echo "$ppl $baseline_ppl $MAX_PPL_REGRESSION_PCT" | \
            awk '{regression = (($1 - $2) / $2) * 100; print (regression > $3) ? "1" : "0"}')

        if [ "$exceeded" = "1" ]; then
            regression=$(echo "$ppl $baseline_ppl" | awk '{printf "%.2f", (($1 - $2) / $2) * 100}')
            echo "FAILED: $cache_type PPL regression ${regression}% exceeds ${MAX_PPL_REGRESSION_PCT}% threshold"
            num_failed=$((num_failed + 1))
        fi
    done
    fi

    for mixed in "${MIXED_CACHE_TYPES[@]}"; do
        ppl="${mixed_ppl_results[$mixed]}"
        k_type="${mixed%%:*}"
        v_type="${mixed##*:}"
        exceeded=$(echo "$ppl $baseline_ppl $MAX_PPL_REGRESSION_PCT" | \
            awk '{regression = (($1 - $2) / $2) * 100; print (regression > $3) ? "1" : "0"}')

        if [ "$exceeded" = "1" ]; then
            regression=$(echo "$ppl $baseline_ppl" | awk '{printf "%.2f", (($1 - $2) / $2) * 100}')
            echo "FAILED: K=$k_type V=$v_type PPL regression ${regression}% exceeds ${MAX_PPL_REGRESSION_PCT}% threshold"
            num_failed=$((num_failed + 1))
        fi
    done

    if [ "$MIXED_ONLY" = false ]; then
    pq3_ppl="${ppl_results[pq3_0]}"
    pq4_ppl="${ppl_results[pq4_0]}"
    pq4_worse=$(echo "$pq4_ppl $pq3_ppl" | awk '{print ($1 > $2) ? "1" : "0"}')
    if [ "$pq4_worse" = "1" ]; then
        echo "FAILED: pq4_0 PPL ($pq4_ppl) should be <= pq3_0 PPL ($pq3_ppl)"
        num_failed=$((num_failed + 1))
    fi

    tbq3_ppl="${ppl_results[tbq3_0]}"
    tbq4_ppl="${ppl_results[tbq4_0]}"
    tbq3_worse=$(echo "$tbq3_ppl $pq3_ppl" | awk '{print ($1 > $2) ? "1" : "0"}')
    if [ "$tbq3_worse" = "1" ]; then
        echo "WARNING: tbq3_0 PPL ($tbq3_ppl) should be <= pq3_0 PPL ($pq3_ppl)"
    fi
    tbq4_worse=$(echo "$tbq4_ppl $pq4_ppl" | awk '{print ($1 > $2) ? "1" : "0"}')
    if [ "$tbq4_worse" = "1" ]; then
        echo "WARNING: tbq4_0 PPL ($tbq4_ppl) should be <= pq4_0 PPL ($pq4_ppl)"
    fi
    fi

    # --- Write CSV rows with comparison columns ---

    CTX_SWEEP_STR="${N_CTX_LIST[*]}"

    if [ -n "$CSV_FILE" ]; then
        csv_regression_sd() {
            echo "$1 $2" | awk '{printf "%.2f", ($1 / $2) * 100}'
        }
        csv_ratio_sd() {
            echo "$1 $2 $3 $4" | awk '{
                if ($3 > 0) {
                    a = ($2/$3)^2; b = ($1*$4/($3*$3))^2;
                    printf "%.2f", sqrt(a+b)
                } else print ""
            }'
        }

        if [ "$MIXED_ONLY" = false ]; then
        for cache_type in "${CACHE_TYPES[@]}"; do
            ppl="${ppl_results[$cache_type]}"
            ppl_sd="${ppl_sd_results[$cache_type]}"
            elapsed="${time_results[$cache_type]}"
            elapsed_sd="${time_sd_results[$cache_type]}"
            if [ "$cache_type" = "f16" ]; then
                ppl_vs_f16="0.00"
                ppl_vs_f16_sd="0.00"
                time_vs_f16="1.00"
                time_vs_f16_sd="0.00"
            else
                ppl_vs_f16=$(echo "$ppl $baseline_ppl" | awk '{printf "%.2f", (($1 - $2) / $2) * 100}')
                ppl_vs_f16_sd=$(csv_regression_sd "$ppl_sd" "$baseline_ppl")
                time_vs_f16=$(echo "$elapsed $baseline_time" | awk '{if ($2 > 0) printf "%.2f", $1/$2; else print ""}')
                time_vs_f16_sd=$(csv_ratio_sd "$elapsed" "$elapsed_sd" "$baseline_time" "$baseline_time_sd")
            fi
            csv_append "$cache_type" "$cache_type" "no" "$N_CHUNKS_CFG" "$CTX_SWEEP_STR" "$ppl" "$ppl_sd" "$elapsed" "$elapsed_sd" "$ppl_vs_f16" "$ppl_vs_f16_sd" "$time_vs_f16" "$time_vs_f16_sd" "$cfg" "$baseline_ppl"
        done
        fi

        for mixed in "${MIXED_CACHE_TYPES[@]}"; do
            k_type="${mixed%%:*}"
            v_type="${mixed##*:}"
            ppl="${mixed_ppl_results[$mixed]}"
            ppl_sd="${mixed_ppl_sd_results[$mixed]}"
            elapsed="${mixed_time_results[$mixed]}"
            elapsed_sd="${mixed_time_sd_results[$mixed]}"
            ppl_vs_f16=$(echo "$ppl $baseline_ppl" | awk '{printf "%.2f", (($1 - $2) / $2) * 100}')
            ppl_vs_f16_sd=$(csv_regression_sd "$ppl_sd" "$baseline_ppl")
            time_vs_f16=$(echo "$elapsed $baseline_time" | awk '{if ($2 > 0) printf "%.2f", $1/$2; else print ""}')
            time_vs_f16_sd=$(csv_ratio_sd "$elapsed" "$elapsed_sd" "$baseline_time" "$baseline_time_sd")
            csv_append "$k_type" "$v_type" "yes" "$N_CHUNKS_CFG" "$CTX_SWEEP_STR" "$ppl" "$ppl_sd" "$elapsed" "$elapsed_sd" "$ppl_vs_f16" "$ppl_vs_f16_sd" "$time_vs_f16" "$time_vs_f16_sd" "$cfg" "$baseline_ppl"
        done

        # Alpha-scaled CSV rows
        NC_FLAG="on"
        if [ "$MIXED_ONLY" = false ]; then
            for cache_type in "${CACHE_TYPES[@]}"; do
                [ -z "${ppl_results_a[$cache_type]:-}" ] && continue
                ppl="${ppl_results_a[$cache_type]}"
                ppl_sd="${ppl_sd_results_a[$cache_type]}"
                elapsed="${time_results_a[$cache_type]}"
                elapsed_sd="${time_sd_results_a[$cache_type]}"
                ppl_vs_f16=$(echo "$ppl $baseline_ppl" | awk '{printf "%.2f", (($1 - $2) / $2) * 100}')
                ppl_vs_f16_sd=$(csv_regression_sd "$ppl_sd" "$baseline_ppl")
                time_vs_f16=$(echo "$elapsed $baseline_time" | awk '{if ($2 > 0) printf "%.2f", $1/$2; else print ""}')
                time_vs_f16_sd=$(csv_ratio_sd "$elapsed" "$elapsed_sd" "$baseline_time" "$baseline_time_sd")
                csv_append "$cache_type" "$cache_type" "no" "$N_CHUNKS_CFG" "$CTX_SWEEP_STR" "$ppl" "$ppl_sd" "$elapsed" "$elapsed_sd" "$ppl_vs_f16" "$ppl_vs_f16_sd" "$time_vs_f16" "$time_vs_f16_sd" "$cfg" "$baseline_ppl"
            done
            fi
            for mixed in "${MIXED_CACHE_TYPES[@]}"; do
                [ -z "${mixed_ppl_results_a[$mixed]:-}" ] && continue
                k_type="${mixed%%:*}"
                v_type="${mixed##*:}"
                ppl="${mixed_ppl_results_a[$mixed]}"
                ppl_sd="${mixed_ppl_sd_results_a[$mixed]}"
                elapsed="${mixed_time_results_a[$mixed]}"
                elapsed_sd="${mixed_time_sd_results_a[$mixed]}"
                ppl_vs_f16=$(echo "$ppl $baseline_ppl" | awk '{printf "%.2f", (($1 - $2) / $2) * 100}')
                ppl_vs_f16_sd=$(csv_regression_sd "$ppl_sd" "$baseline_ppl")
                time_vs_f16=$(echo "$elapsed $baseline_time" | awk '{if ($2 > 0) printf "%.2f", $1/$2; else print ""}')
                time_vs_f16_sd=$(csv_ratio_sd "$elapsed" "$elapsed_sd" "$baseline_time" "$baseline_time_sd")
                csv_append "$k_type" "$v_type" "yes" "$N_CHUNKS_CFG" "$CTX_SWEEP_STR" "$ppl" "$ppl_sd" "$elapsed" "$elapsed_sd" "$ppl_vs_f16" "$ppl_vs_f16_sd" "$time_vs_f16" "$time_vs_f16_sd" "$cfg" "$baseline_ppl"
            done
        NC_FLAG="off"
    fi

    # Clean up per-config associative arrays
    unset ppl_results ppl_sd_results time_results time_sd_results
    unset ppl_results_a ppl_sd_results_a time_results_a time_sd_results_a
    unset mixed_ppl_results mixed_ppl_sd_results mixed_time_results mixed_time_sd_results
    unset mixed_ppl_results_a mixed_ppl_sd_results_a mixed_time_results_a mixed_time_sd_results_a

done  # end config loop

echo ""
echo "GPU device: $GPU_DEVICE"
if [ "$num_failed" -eq 0 ]; then
    echo "All checks passed."
else
    echo "$num_failed check(s) failed."
fi
if [ -n "$CSV_FINAL" ]; then
    cp "$CSV_FILE" "$CSV_FINAL"
    rm -f "$CSV_FILE"
    echo "Results saved to: $CSV_FINAL (${#CSV_ROWS[@]} rows)"
    echo "Log saved to:     $LOG_FILE"
fi
