#!/usr/bin/env bash
#
# Benchmark KV cache quantization throughput (prefill pp & decode tg t/s).
# Auto-detects coopmat1/coopmat2 GPU support and compares cooperative matrix
# flash attention vs scalar fallback for TBQ/PQ quantizations.
#
# Usage:
#   tests/test-kv-cache-quantization-perf.sh [options] [build_dir]
#
# Options:
#   -c <tiny|small|mid|large>     Size config preset (repeatable, default: small)
#   -r <n>                       Override preset repetitions (applies to all configs)
#   --csv <file>                 Write results to specific CSV file (auto-generated by default)
#
# Config presets (pp / tg / reps):
#   tiny   — pp 128,  tg 32,  reps 1  (very quick smoke test)
#   small  — pp 128,  tg 32,  reps 3  (quick with stdev)
#   mid    — pp 512,  tg 128, reps 3  (balanced with stdev)
#   large  — pp 2048, tg 512, reps 5  (full stress test with stdev)
#
# Without -c, env vars PROMPT_LEN, GEN_LEN, REPS are used directly.
#
# Environment variables:
#   MODEL_DIR    — directory for model files (default: models)
#   MODEL_NAME   — GGUF filename
#   MODEL_URL    — download URL
#   PROMPT_LEN   — prompt length when no -c given (default: 512)
#   GEN_LEN      — gen length when no -c given (default: 128)
#   REPS         — repetitions when no -c given (default: 3)
#   CSV          — set to 0 to disable auto CSV output (default: 1)
#   SKIP_COOPMAT_COMPARE — set to 1 to skip the coopmat-disabled runs
#   FORCE_COOPMAT — override autodetect: "cm1", "cm2", "both", or "none"
#
# Examples:
#   tests/test-kv-cache-quantization-perf.sh -c small -c mid --csv results.csv
#   tests/test-kv-cache-quantization-perf.sh -c large -r 10 --csv results.csv build
#   PROMPT_LEN=256 GEN_LEN=64 REPS=5 tests/test-kv-cache-quantization-perf.sh build
#
set -euo pipefail

# --- Parse arguments ---

CONFIGS=()
REPS_ARG=""
CSV_FILE=""
BUILD_DIR=""

while [ $# -gt 0 ]; do
    case "$1" in
        -c)
            shift
            CONFIGS+=("$1")
            shift
            ;;
        -r)
            shift
            REPS_ARG="$1"
            shift
            ;;
        --csv)
            shift
            CSV_FILE="$1"
            shift
            ;;
        -h|--help)
            head -36 "$0" | tail -35
            exit 0
            ;;
        *)
            BUILD_DIR="$1"
            shift
            ;;
    esac
done

BUILD_DIR="${BUILD_DIR:-build}"
BENCH="$BUILD_DIR/bin/llama-bench"

MODEL_DIR="${MODEL_DIR:-models}"
MODEL_NAME="${MODEL_NAME:-Mistral-7B-Instruct-v0.3-Q4_K_S.gguf}"
MODEL_URL="${MODEL_URL:-https://huggingface.co/bartowski/Mistral-7B-Instruct-v0.3-GGUF/resolve/main/Mistral-7B-Instruct-v0.3-Q4_K_S.gguf}"
MODEL_PATH="$MODEL_DIR/$MODEL_NAME"

SKIP_COOPMAT_COMPARE="${SKIP_COOPMAT_COMPARE:-0}"
FORCE_COOPMAT="${FORCE_COOPMAT:-}"

# When no -c is given, default to small
if [ ${#CONFIGS[@]} -eq 0 ]; then
    CONFIGS=("small")
fi


# --- Config presets ---

config_prompt_len() {
    case "$1" in
        tiny)  echo 128  ;;
        small) echo 128  ;;
        mid)   echo 512  ;;
        large) echo 2048 ;;
        env)   echo "${PROMPT_LEN:-512}" ;;
        *) echo "Error: unknown config '$1' (expected tiny, small, mid, large)" >&2; exit 1 ;;
    esac
}

config_gen_len() {
    case "$1" in
        tiny)  echo 32  ;;
        small) echo 32  ;;
        mid)   echo 128 ;;
        large) echo 512 ;;
        env)   echo "${GEN_LEN:-128}" ;;
        *) echo "Error: unknown config '$1'" >&2; exit 1 ;;
    esac
}

config_reps() {
    case "$1" in
        tiny)  echo 1 ;;
        small) echo 3 ;;
        mid)   echo 3 ;;
        large) echo 5 ;;
        env)   echo "${REPS:-3}" ;;
        *) echo "Error: unknown config '$1'" >&2; exit 1 ;;
    esac
}

# --- Validate ---

if [ ! -f "$BENCH" ]; then
    echo "Error: $BENCH not found. Build the project first."
    echo "  cmake -B $BUILD_DIR && cmake --build $BUILD_DIR -j\$(nproc)"
    exit 1
fi

mkdir -p "$MODEL_DIR"

if [ ! -f "$MODEL_PATH" ] || [ "$(stat -c%s "$MODEL_PATH" 2>/dev/null || echo 0)" -lt 1000000 ]; then
    [ -f "$MODEL_PATH" ] && rm -f "$MODEL_PATH"
    echo "Downloading model: $MODEL_NAME ..."
    if command -v curl &> /dev/null; then
        curl -L --fail -C - -o "$MODEL_PATH" "$MODEL_URL"
    elif command -v wget &> /dev/null; then
        wget -O "$MODEL_PATH" "$MODEL_URL"
    else
        echo "Error: neither curl nor wget found"
        exit 1
    fi
    FILE_SIZE=$(stat -c%s "$MODEL_PATH" 2>/dev/null || echo 0)
    if [ "$FILE_SIZE" -lt 1000000 ]; then
        echo "Error: downloaded file is only $FILE_SIZE bytes."
        rm -f "$MODEL_PATH"
        exit 1
    fi
    echo "Model downloaded to $MODEL_PATH ($((FILE_SIZE / 1048576)) MB)"
else
    echo "Model already exists: $MODEL_PATH"
fi

# --- GPU device detection ---

detect_gpu_device() {
    local gpu_info=""

    if [ -f "$BENCH" ]; then
        gpu_info=$("$BENCH" --list-devices 2>&1 | grep -E '^\s+(Vulkan|CUDA|Metal|SYCL|ROCm)' | head -1 | sed 's/^[[:space:]]*//' || true)
    fi

    if [ -z "$gpu_info" ]; then
        if command -v nvidia-smi &> /dev/null; then
            gpu_info=$(nvidia-smi --query-gpu=name --format=csv,noheader 2>/dev/null | head -1 || true)
        elif command -v vulkaninfo &> /dev/null; then
            gpu_info=$(vulkaninfo 2>/dev/null | grep "deviceName" | head -1 | sed 's/.*= //' || true)
        fi
    fi

    echo "${gpu_info:-unknown}"
}

GPU_DEVICE=$(detect_gpu_device)

# Auto-generate CSV filename unless explicitly provided or disabled (CSV=0)
CSV_FINAL=""
if [ -z "$CSV_FILE" ] && [ "${CSV:-1}" != "0" ]; then
    sanitize() { echo "$1" | tr '[:upper:]' '[:lower:]' | sed 's/[^a-z0-9._-]/_/g; s/__*/_/g; s/^_//; s/_$//'; }
    GPU_SHORT=$(echo "$GPU_DEVICE" | sed 's/^[A-Za-z]*[0-9]*: //; s/ ([0-9].*//')
    GPU_TAG=$(sanitize "$GPU_SHORT")
    MODEL_TAG=$(sanitize "${MODEL_NAME%.gguf}")
    CFG_TAG=$(printf '%s-' "${CONFIGS[@]}" | sed 's/-$//')
    CSV_FILE="kv-perf_${GPU_TAG}_${MODEL_TAG}_${CFG_TAG}_$(date +%Y%m%d_%H%M%S).csv"
fi
if [ -n "$CSV_FILE" ]; then
    CSV_FINAL="$CSV_FILE"
    CSV_FILE=$(mktemp /tmp/kv-perf-XXXXXX.csv)
fi

# --- Log file setup (same name as CSV, .txt extension) ---

LOG_FILE=""
if [ -n "$CSV_FINAL" ]; then
    LOG_FILE="${CSV_FINAL%.csv}.txt"
    exec > >(tee -a "$LOG_FILE") 2>&1
fi

# --- Detect coopmat support ---

detect_coopmat() {
    if [ -n "$FORCE_COOPMAT" ]; then
        echo "$FORCE_COOPMAT"
        return
    fi

    if ! command -v vulkaninfo &> /dev/null; then
        echo "Warning: vulkaninfo not found, cannot autodetect coopmat. Assuming none." >&2
        echo "none"
        return
    fi

    local vk_extensions
    vk_extensions=$(vulkaninfo 2>/dev/null || true)

    if [ -z "$vk_extensions" ]; then
        echo "Warning: vulkaninfo produced no output, assuming no coopmat support." >&2
        echo "none"
        return
    fi

    local has_cm1=0 has_cm2=0
    grep -q "VK_KHR_cooperative_matrix" <<< "$vk_extensions" && has_cm1=1
    grep -q "VK_NV_cooperative_matrix2" <<< "$vk_extensions" && has_cm2=1

    if [ "$has_cm1" = "1" ] && [ "$has_cm2" = "1" ]; then
        echo "both"
    elif [ "$has_cm2" = "1" ]; then
        echo "cm2"
    elif [ "$has_cm1" = "1" ]; then
        echo "cm1"
    else
        echo "none"
    fi
}

COOPMAT_LEVEL=$(detect_coopmat)

COOPMAT_LEVELS=()
case "$COOPMAT_LEVEL" in
    both)
        COOPMAT_LEVELS=("cm1" "cm2")
        ;;
    cm2)
        COOPMAT_LEVELS=("cm2")
        ;;
    cm1)
        COOPMAT_LEVELS=("cm1")
        ;;
    none)
        COOPMAT_LEVELS=()
        SKIP_COOPMAT_COMPARE=1
        ;;
    *)
        echo "Error: unknown FORCE_COOPMAT value '$COOPMAT_LEVEL' (expected cm1, cm2, both, or none)"
        exit 1
        ;;
esac

coopmat_label_for() {
    case "$1" in
        cm1) echo "coopmat1" ;;
        cm2) echo "coopmat2" ;;
        *)   echo "scalar"  ;;
    esac
}

coopmat_env_for() {
    case "$1" in
        cm1) echo "GGML_VK_DISABLE_COOPMAT2=1" ;;
        cm2) echo "" ;;
        *)   echo "GGML_VK_DISABLE_COOPMAT=1 GGML_VK_DISABLE_COOPMAT2=1" ;;
    esac
}

SCALAR_DISABLE_ENV="GGML_VK_DISABLE_COOPMAT=1 GGML_VK_DISABLE_COOPMAT2=1"

if [ ${#COOPMAT_LEVELS[@]} -gt 0 ]; then
    COOPMAT_DISPLAY=$(printf '%s+' "${COOPMAT_LEVELS[@]}")
    COOPMAT_DISPLAY="${COOPMAT_DISPLAY%+}"
else
    COOPMAT_DISPLAY="none"
fi

# --- Config ---

SAME_TYPE_CONFIGS=("f16" "q8_0" "q4_0" "tbq3_0" "tbq4_0" "pq3_0" "pq4_0")

MIXED_CONFIGS=(
    "tbq3_0:pq3_0"
    "tbq4_0:pq4_0"
    "tbq3_0:q8_0"
    "tbq4_0:f16"
)

# --- Extraction helpers (avg ± stdev) ---

extract_pp() {
    echo "$1" | grep -E '^\|' | grep -E '\bpp[0-9]' | awk -F'|' '{n=NF; gsub(/ /, "", $(n-1)); split($(n-1), a, "±"); print a[1]}' | tail -1
}

extract_pp_stdev() {
    echo "$1" | grep -E '^\|' | grep -E '\bpp[0-9]' | awk -F'|' '{n=NF; gsub(/ /, "", $(n-1)); split($(n-1), a, "±"); print a[2]}' | tail -1
}

extract_tg() {
    echo "$1" | grep -E '^\|' | grep -E '\btg[0-9]' | awk -F'|' '{n=NF; gsub(/ /, "", $(n-1)); split($(n-1), a, "±"); print a[1]}' | tail -1
}

extract_tg_stdev() {
    echo "$1" | grep -E '^\|' | grep -E '\btg[0-9]' | awk -F'|' '{n=NF; gsub(/ /, "", $(n-1)); split($(n-1), a, "±"); print a[2]}' | tail -1
}

run_bench() {
    local k_type="$1"
    local v_type="$2"
    local env_prefix="$3"
    local label="$4"
    local prompt_len="$5"
    local gen_len="$6"
    local reps="$7"

    local output
    output=$(env $env_prefix "$BENCH" \
        -m "$MODEL_PATH" \
        --cache-type-k "$k_type" \
        --cache-type-v "$v_type" \
        -fa 1 \
        -p "$prompt_len" \
        -n "$gen_len" \
        -r "$reps" \
        2>&1) || {
        echo "  FAILED: $label (K=$k_type V=$v_type)" >&2
        echo "$output" | tail -5 >&2
        return 1
    }

    if echo "$output" | grep -q "error:"; then
        echo "  FAILED: $label (K=$k_type V=$v_type) — $(echo "$output" | grep 'error:' | head -1)" >&2
        return 1
    fi

    local pp pp_sd tg tg_sd
    pp=$(extract_pp "$output")
    pp_sd=$(extract_pp_stdev "$output")
    tg=$(extract_tg "$output")
    tg_sd=$(extract_tg_stdev "$output")

    if [ -z "$pp" ] || [ -z "$tg" ]; then
        echo "  FAILED: $label — could not parse t/s from output" >&2
        return 1
    fi

    pp_sd="${pp_sd:-0.00}"
    tg_sd="${tg_sd:-0.00}"

    echo "$pp $pp_sd $tg $tg_sd"
}

# --- CSV setup ---

CSV_ROWS=()

csv_init() {
    if [ -n "$CSV_FILE" ]; then
        echo "gpu_device,model,config,coopmat_mode,cache_k,cache_v,mixed,prompt_len,gen_len,reps,pp_avg,pp_stdev,tg_avg,tg_stdev,pp_vs_f16_x,tg_vs_f16_x,pp_speedup_vs_scalar,tg_speedup_vs_scalar" > "$CSV_FILE"
    fi
}

csv_append() {
    local cm_mode="$1" k_type="$2" v_type="$3" is_mixed="$4" prompt_len="$5" gen_len="$6"
    local pp_avg="$7" pp_sd="$8" tg_avg="$9" tg_sd="${10}" config_name="${11}" reps="${12}"
    local pp_vs_f16="${13}" tg_vs_f16="${14}" pp_vs_scalar="${15}" tg_vs_scalar="${16}"
    local row="\"$GPU_DEVICE\",\"$MODEL_NAME\",\"$config_name\",\"$cm_mode\",\"$k_type\",\"$v_type\",\"$is_mixed\",$prompt_len,$gen_len,$reps,$pp_avg,$pp_sd,$tg_avg,$tg_sd,$pp_vs_f16,$tg_vs_f16,$pp_vs_scalar,$tg_vs_scalar"
    CSV_ROWS+=("$row")
    if [ -n "$CSV_FILE" ]; then
        echo "$row" >> "$CSV_FILE"
    fi
}

csv_init

# --- Print header ---

echo ""
echo "=========================================="
echo " KV Cache Quantization Performance Test"
echo "=========================================="
echo " GPU:         $GPU_DEVICE"
echo " Model:       $MODEL_NAME"
echo " Configs:     ${CONFIGS[*]}"
for cfg_info in "${CONFIGS[@]}"; do
    local_pp=$(config_prompt_len "$cfg_info")
    local_tg=$(config_gen_len "$cfg_info")
    local_reps=$(config_reps "$cfg_info")
    [ -n "$REPS_ARG" ] && local_reps="$REPS_ARG"
    echo "   $cfg_info: pp=$local_pp tg=$local_tg reps=$local_reps"
done
if [ -n "$REPS_ARG" ]; then
    echo " Reps override: $REPS_ARG"
fi
echo " GPU coopmat: $COOPMAT_LEVEL ($COOPMAT_DISPLAY)"
if [ "$SKIP_COOPMAT_COMPARE" = "1" ]; then
    echo " Compare:     disabled"
else
    for lvl in "${COOPMAT_LEVELS[@]}"; do
        echo " Compare:     $(coopmat_label_for "$lvl") vs scalar"
    done
fi
if [ -n "$CSV_FINAL" ]; then
    echo " CSV output:  $CSV_FINAL"
    echo " Log output:  $LOG_FILE"
fi
echo "=========================================="
echo ""

# --- Main benchmark loop over configs ---

for cfg in "${CONFIGS[@]}"; do
    PROMPT_LEN_CFG=$(config_prompt_len "$cfg")
    GEN_LEN_CFG=$(config_gen_len "$cfg")
    REPS_CFG=$(config_reps "$cfg")
    [ -n "$REPS_ARG" ] && REPS_CFG="$REPS_ARG"

    echo ""
    echo "############################################"
    echo " Config: $cfg  (pp=$PROMPT_LEN_CFG, tg=$GEN_LEN_CFG, reps=$REPS_CFG)"
    echo "############################################"
    echo ""

    # --- Same-type benchmarks ---

    declare -A pp_scalar tg_scalar ppsd_scalar tgsd_scalar

    echo "--- Same-type KV cache configs [$cfg] ---"
    echo ""

    for lvl in "${COOPMAT_LEVELS[@]}"; do
        declare -A "pp_${lvl}" "tg_${lvl}" "ppsd_${lvl}" "tgsd_${lvl}"
        local_label=$(coopmat_label_for "$lvl")
        local_env=$(coopmat_env_for "$lvl")

        for cache_type in "${SAME_TYPE_CONFIGS[@]}"; do
            echo "Running: K=$cache_type V=$cache_type ($local_label, $cfg) ..."
            result=$(run_bench "$cache_type" "$cache_type" "$local_env" "$local_label" "$PROMPT_LEN_CFG" "$GEN_LEN_CFG" "$REPS_CFG") || continue
            eval "pp_${lvl}[\"$cache_type\"]=$(echo "$result" | awk '{print $1}')"
            eval "ppsd_${lvl}[\"$cache_type\"]=$(echo "$result" | awk '{print $2}')"
            eval "tg_${lvl}[\"$cache_type\"]=$(echo "$result" | awk '{print $3}')"
            eval "tgsd_${lvl}[\"$cache_type\"]=$(echo "$result" | awk '{print $4}')"
            eval "echo \"  pp=\${pp_${lvl}[$cache_type]}±\${ppsd_${lvl}[$cache_type]} t/s  tg=\${tg_${lvl}[$cache_type]}±\${tgsd_${lvl}[$cache_type]} t/s\""
        done
        echo ""
    done

    if [ ${#COOPMAT_LEVELS[@]} -eq 0 ]; then
        for cache_type in "${SAME_TYPE_CONFIGS[@]}"; do
            echo "Running: K=$cache_type V=$cache_type (scalar, $cfg) ..."
            result=$(run_bench "$cache_type" "$cache_type" "" "scalar" "$PROMPT_LEN_CFG" "$GEN_LEN_CFG" "$REPS_CFG") || continue
            pp_scalar["$cache_type"]=$(echo "$result" | awk '{print $1}')
            ppsd_scalar["$cache_type"]=$(echo "$result" | awk '{print $2}')
            tg_scalar["$cache_type"]=$(echo "$result" | awk '{print $3}')
            tgsd_scalar["$cache_type"]=$(echo "$result" | awk '{print $4}')
            echo "  pp=${pp_scalar[$cache_type]}±${ppsd_scalar[$cache_type]} t/s  tg=${tg_scalar[$cache_type]}±${tgsd_scalar[$cache_type]} t/s"
        done
        echo ""
    fi

    if [ "$SKIP_COOPMAT_COMPARE" != "1" ]; then
        for cache_type in "${SAME_TYPE_CONFIGS[@]}"; do
            echo "Running: K=$cache_type V=$cache_type (scalar, $cfg) ..."
            result=$(run_bench "$cache_type" "$cache_type" "$SCALAR_DISABLE_ENV" "scalar" "$PROMPT_LEN_CFG" "$GEN_LEN_CFG" "$REPS_CFG") || continue
            pp_scalar["$cache_type"]=$(echo "$result" | awk '{print $1}')
            ppsd_scalar["$cache_type"]=$(echo "$result" | awk '{print $2}')
            tg_scalar["$cache_type"]=$(echo "$result" | awk '{print $3}')
            tgsd_scalar["$cache_type"]=$(echo "$result" | awk '{print $4}')
            echo "  pp=${pp_scalar[$cache_type]}±${ppsd_scalar[$cache_type]} t/s  tg=${tg_scalar[$cache_type]}±${tgsd_scalar[$cache_type]} t/s"
        done
    fi

    # --- Same-type summary ---

    print_same_type_table() {
        local lvl="$1"
        local cm_tag
        cm_tag=$(coopmat_label_for "$lvl")

        echo ""
        echo "=========================================="
        echo " Same-Type Results [$cfg]: $cm_tag vs scalar (t/s)"
        echo "=========================================="

        printf "  %-10s %14s %14s %10s %14s %14s %10s\n" \
            "Type" "pp($cm_tag)" "pp(scalar)" "pp speedup" "tg($cm_tag)" "tg(scalar)" "tg speedup"
        printf "  %-10s %14s %14s %10s %14s %14s %10s\n" \
            "----" "-------" "----------" "----------" "------" "---------" "----------"

        for cache_type in "${SAME_TYPE_CONFIGS[@]}"; do
            local p_on="" p_on_sd="" p_off="" t_on="" t_on_sd="" t_off="" pp_speedup="n/a" tg_speedup="n/a"
            eval "p_on=\${pp_${lvl}[\$cache_type]:-n/a}"
            eval "p_on_sd=\${ppsd_${lvl}[\$cache_type]:-}"
            p_off="${pp_scalar[$cache_type]:-n/a}"
            eval "t_on=\${tg_${lvl}[\$cache_type]:-n/a}"
            eval "t_on_sd=\${tgsd_${lvl}[\$cache_type]:-}"
            t_off="${tg_scalar[$cache_type]:-n/a}"
            if [ "$p_on" != "n/a" ] && [ "$p_off" != "n/a" ]; then
                pp_speedup=$(echo "$p_on $p_off" | awk '{if ($2 > 0) printf "%.2fx", $1/$2; else print "n/a"}')
            fi
            if [ "$t_on" != "n/a" ] && [ "$t_off" != "n/a" ]; then
                tg_speedup=$(echo "$t_on $t_off" | awk '{if ($2 > 0) printf "%.2fx", $1/$2; else print "n/a"}')
            fi
            local pp_display="$p_on"
            local tg_display="$t_on"
            [ -n "$p_on_sd" ] && [ "$p_on" != "n/a" ] && pp_display="${p_on}±${p_on_sd}"
            [ -n "$t_on_sd" ] && [ "$t_on" != "n/a" ] && tg_display="${t_on}±${t_on_sd}"
            printf "  %-10s %14s %14s %10s %14s %14s %10s\n" \
                "$cache_type" "$pp_display" "$p_off" "$pp_speedup" "$tg_display" "$t_off" "$tg_speedup"
        done

        echo "=========================================="
    }

    print_same_type_vs_f16_table() {
        local lvl="$1"
        local cm_tag
        cm_tag=$(coopmat_label_for "$lvl")

        local f16_pp_on="" f16_tg_on="" f16_pp_off="" f16_tg_off=""
        eval "f16_pp_on=\${pp_${lvl}[f16]:-}"
        eval "f16_tg_on=\${tg_${lvl}[f16]:-}"
        f16_pp_off="${pp_scalar[f16]:-}"
        f16_tg_off="${tg_scalar[f16]:-}"

        echo ""
        echo "=========================================="
        echo " Same-Type vs f16 Baseline [$cfg]: $cm_tag + scalar"
        echo "=========================================="

        printf "  %-10s %12s %12s %12s %12s\n" \
            "Type" "pp($cm_tag)" "pp(scalar)" "tg($cm_tag)" "tg(scalar)"
        printf "  %-10s %12s %12s %12s %12s\n" \
            "----" "-------" "----------" "------" "---------"

        for cache_type in "${SAME_TYPE_CONFIGS[@]}"; do
            local p_on="" t_on="" p_off="" t_off=""
            local pp_vs_f16_on="n/a" tg_vs_f16_on="n/a" pp_vs_f16_off="n/a" tg_vs_f16_off="n/a"
            eval "p_on=\${pp_${lvl}[\$cache_type]:-}"
            eval "t_on=\${tg_${lvl}[\$cache_type]:-}"
            p_off="${pp_scalar[$cache_type]:-}"
            t_off="${tg_scalar[$cache_type]:-}"

            if [ "$cache_type" = "f16" ]; then
                pp_vs_f16_on="(baseline)"
                tg_vs_f16_on="(baseline)"
                pp_vs_f16_off="(baseline)"
                tg_vs_f16_off="(baseline)"
            else
                [ -n "$p_on" ] && [ -n "$f16_pp_on" ] && \
                    pp_vs_f16_on=$(echo "$p_on $f16_pp_on" | awk '{if ($2 > 0) printf "%.2fx", $1/$2; else print "n/a"}')
                [ -n "$t_on" ] && [ -n "$f16_tg_on" ] && \
                    tg_vs_f16_on=$(echo "$t_on $f16_tg_on" | awk '{if ($2 > 0) printf "%.2fx", $1/$2; else print "n/a"}')
                [ -n "$p_off" ] && [ -n "$f16_pp_off" ] && \
                    pp_vs_f16_off=$(echo "$p_off $f16_pp_off" | awk '{if ($2 > 0) printf "%.2fx", $1/$2; else print "n/a"}')
                [ -n "$t_off" ] && [ -n "$f16_tg_off" ] && \
                    tg_vs_f16_off=$(echo "$t_off $f16_tg_off" | awk '{if ($2 > 0) printf "%.2fx", $1/$2; else print "n/a"}')
            fi

            printf "  %-10s %12s %12s %12s %12s\n" \
                "$cache_type" "$pp_vs_f16_on" "$pp_vs_f16_off" "$tg_vs_f16_on" "$tg_vs_f16_off"
        done

        echo "=========================================="
    }

    if [ "$SKIP_COOPMAT_COMPARE" != "1" ]; then
        for lvl in "${COOPMAT_LEVELS[@]}"; do
            print_same_type_table "$lvl"
            print_same_type_vs_f16_table "$lvl"
        done
    else
        echo ""
        echo "=========================================="
        echo " Same-Type Results [$cfg] (t/s, mean±stdev)"
        echo "=========================================="

        printf "  %-10s %16s %16s\n" "Type" "pp" "tg"
        printf "  %-10s %16s %16s\n" "----" "--" "--"

        local f16_pp_s="${pp_scalar[f16]:-}"
        local f16_tg_s="${tg_scalar[f16]:-}"

        for cache_type in "${SAME_TYPE_CONFIGS[@]}"; do
            local pp_v="${pp_scalar[$cache_type]:-n/a}"
            local pp_sd="${ppsd_scalar[$cache_type]:-}"
            local tg_v="${tg_scalar[$cache_type]:-n/a}"
            local tg_sd="${tgsd_scalar[$cache_type]:-}"
            local pp_d="$pp_v" tg_d="$tg_v"
            [ -n "$pp_sd" ] && [ "$pp_v" != "n/a" ] && pp_d="${pp_v}±${pp_sd}"
            [ -n "$tg_sd" ] && [ "$tg_v" != "n/a" ] && tg_d="${tg_v}±${tg_sd}"
            printf "  %-10s %16s %16s\n" "$cache_type" "$pp_d" "$tg_d"
        done

        echo "=========================================="

        echo ""
        echo "=========================================="
        echo " Same-Type vs f16 Baseline [$cfg]"
        echo "=========================================="

        printf "  %-10s %12s %12s\n" "Type" "pp vs f16" "tg vs f16"
        printf "  %-10s %12s %12s\n" "----" "---------" "---------"

        for cache_type in "${SAME_TYPE_CONFIGS[@]}"; do
            if [ "$cache_type" = "f16" ]; then
                printf "  %-10s %12s %12s\n" "$cache_type" "(baseline)" "(baseline)"
            else
                local pp_v="${pp_scalar[$cache_type]:-}"
                local tg_v="${tg_scalar[$cache_type]:-}"
                local pp_r="n/a" tg_r="n/a"
                [ -n "$pp_v" ] && [ -n "$f16_pp_s" ] && \
                    pp_r=$(echo "$pp_v $f16_pp_s" | awk '{if ($2 > 0) printf "%.2fx", $1/$2; else print "n/a"}')
                [ -n "$tg_v" ] && [ -n "$f16_tg_s" ] && \
                    tg_r=$(echo "$tg_v $f16_tg_s" | awk '{if ($2 > 0) printf "%.2fx", $1/$2; else print "n/a"}')
                printf "  %-10s %12s %12s\n" "$cache_type" "$pp_r" "$tg_r"
            fi
        done

        echo "=========================================="
    fi

    # --- Mixed K/V benchmarks ---

    declare -A mpp_scalar mtg_scalar mppsd_scalar mtgsd_scalar

    echo ""
    echo "--- Mixed K/V cache configs [$cfg] ---"
    echo ""

    for lvl in "${COOPMAT_LEVELS[@]}"; do
        declare -A "mpp_${lvl}" "mtg_${lvl}" "mppsd_${lvl}" "mtgsd_${lvl}"
        local_label=$(coopmat_label_for "$lvl")
        local_env=$(coopmat_env_for "$lvl")

        for mixed in "${MIXED_CONFIGS[@]}"; do
            k_type="${mixed%%:*}"
            v_type="${mixed##*:}"

            echo "Running: K=$k_type V=$v_type ($local_label, $cfg) ..."
            result=$(run_bench "$k_type" "$v_type" "$local_env" "$local_label" "$PROMPT_LEN_CFG" "$GEN_LEN_CFG" "$REPS_CFG") || continue
            eval "mpp_${lvl}[\"$mixed\"]=$(echo "$result" | awk '{print $1}')"
            eval "mppsd_${lvl}[\"$mixed\"]=$(echo "$result" | awk '{print $2}')"
            eval "mtg_${lvl}[\"$mixed\"]=$(echo "$result" | awk '{print $3}')"
            eval "mtgsd_${lvl}[\"$mixed\"]=$(echo "$result" | awk '{print $4}')"
            eval "echo \"  pp=\${mpp_${lvl}[$mixed]}±\${mppsd_${lvl}[$mixed]} t/s  tg=\${mtg_${lvl}[$mixed]}±\${mtgsd_${lvl}[$mixed]} t/s\""
        done
        echo ""
    done

    if [ ${#COOPMAT_LEVELS[@]} -eq 0 ]; then
        for mixed in "${MIXED_CONFIGS[@]}"; do
            k_type="${mixed%%:*}"
            v_type="${mixed##*:}"

            echo "Running: K=$k_type V=$v_type (scalar, $cfg) ..."
            result=$(run_bench "$k_type" "$v_type" "" "scalar" "$PROMPT_LEN_CFG" "$GEN_LEN_CFG" "$REPS_CFG") || continue
            mpp_scalar["$mixed"]=$(echo "$result" | awk '{print $1}')
            mppsd_scalar["$mixed"]=$(echo "$result" | awk '{print $2}')
            mtg_scalar["$mixed"]=$(echo "$result" | awk '{print $3}')
            mtgsd_scalar["$mixed"]=$(echo "$result" | awk '{print $4}')
            echo "  pp=${mpp_scalar[$mixed]}±${mppsd_scalar[$mixed]} t/s  tg=${mtg_scalar[$mixed]}±${mtgsd_scalar[$mixed]} t/s"
        done
        echo ""
    fi

    if [ "$SKIP_COOPMAT_COMPARE" != "1" ]; then
        for mixed in "${MIXED_CONFIGS[@]}"; do
            k_type="${mixed%%:*}"
            v_type="${mixed##*:}"

            echo "Running: K=$k_type V=$v_type (scalar, $cfg) ..."
            result=$(run_bench "$k_type" "$v_type" "$SCALAR_DISABLE_ENV" "scalar" "$PROMPT_LEN_CFG" "$GEN_LEN_CFG" "$REPS_CFG") || continue
            mpp_scalar["$mixed"]=$(echo "$result" | awk '{print $1}')
            mppsd_scalar["$mixed"]=$(echo "$result" | awk '{print $2}')
            mtg_scalar["$mixed"]=$(echo "$result" | awk '{print $3}')
            mtgsd_scalar["$mixed"]=$(echo "$result" | awk '{print $4}')
            echo "  pp=${mpp_scalar[$mixed]}±${mppsd_scalar[$mixed]} t/s  tg=${mtg_scalar[$mixed]}±${mtgsd_scalar[$mixed]} t/s"
        done
    fi

    # --- Mixed summary ---

    print_mixed_table() {
        local lvl="$1"
        local cm_tag
        cm_tag=$(coopmat_label_for "$lvl")

        echo ""
        echo "=========================================="
        echo " Mixed K/V Results [$cfg]: $cm_tag vs scalar (t/s)"
        echo "=========================================="

        printf "  %-10s %-10s %14s %14s %10s %14s %14s %10s\n" \
            "K type" "V type" "pp($cm_tag)" "pp(scalar)" "pp speedup" "tg($cm_tag)" "tg(scalar)" "tg speedup"
        printf "  %-10s %-10s %14s %14s %10s %14s %14s %10s\n" \
            "------" "------" "-------" "----------" "----------" "------" "---------" "----------"

        for mixed in "${MIXED_CONFIGS[@]}"; do
            k_type="${mixed%%:*}"
            v_type="${mixed##*:}"
            local p_on="" p_on_sd="" p_off="" t_on="" t_on_sd="" t_off="" pp_speedup="n/a" tg_speedup="n/a"
            eval "p_on=\${mpp_${lvl}[\$mixed]:-n/a}"
            eval "p_on_sd=\${mppsd_${lvl}[\$mixed]:-}"
            p_off="${mpp_scalar[$mixed]:-n/a}"
            eval "t_on=\${mtg_${lvl}[\$mixed]:-n/a}"
            eval "t_on_sd=\${mtgsd_${lvl}[\$mixed]:-}"
            t_off="${mtg_scalar[$mixed]:-n/a}"
            if [ "$p_on" != "n/a" ] && [ "$p_off" != "n/a" ]; then
                pp_speedup=$(echo "$p_on $p_off" | awk '{if ($2 > 0) printf "%.2fx", $1/$2; else print "n/a"}')
            fi
            if [ "$t_on" != "n/a" ] && [ "$t_off" != "n/a" ]; then
                tg_speedup=$(echo "$t_on $t_off" | awk '{if ($2 > 0) printf "%.2fx", $1/$2; else print "n/a"}')
            fi
            local pp_display="$p_on"
            local tg_display="$t_on"
            [ -n "$p_on_sd" ] && [ "$p_on" != "n/a" ] && pp_display="${p_on}±${p_on_sd}"
            [ -n "$t_on_sd" ] && [ "$t_on" != "n/a" ] && tg_display="${t_on}±${t_on_sd}"
            printf "  %-10s %-10s %14s %14s %10s %14s %14s %10s\n" \
                "$k_type" "$v_type" "$pp_display" "$p_off" "$pp_speedup" "$tg_display" "$t_off" "$tg_speedup"
        done

        echo "=========================================="
    }

    print_mixed_vs_f16_table() {
        local lvl="$1"
        local cm_tag
        cm_tag=$(coopmat_label_for "$lvl")

        local f16_pp_on="" f16_tg_on="" f16_pp_off="" f16_tg_off=""
        eval "f16_pp_on=\${pp_${lvl}[f16]:-}"
        eval "f16_tg_on=\${tg_${lvl}[f16]:-}"
        f16_pp_off="${pp_scalar[f16]:-}"
        f16_tg_off="${tg_scalar[f16]:-}"

        echo ""
        echo "=========================================="
        echo " Mixed K/V vs f16 Baseline [$cfg]: $cm_tag + scalar"
        echo "=========================================="

        printf "  %-10s %-10s %12s %12s %12s %12s\n" \
            "K type" "V type" "pp($cm_tag)" "pp(scalar)" "tg($cm_tag)" "tg(scalar)"
        printf "  %-10s %-10s %12s %12s %12s %12s\n" \
            "------" "------" "-------" "----------" "------" "---------"

        for mixed in "${MIXED_CONFIGS[@]}"; do
            k_type="${mixed%%:*}"
            v_type="${mixed##*:}"
            local p_on="" t_on="" p_off="" t_off=""
            local pp_vs_f16_on="n/a" tg_vs_f16_on="n/a" pp_vs_f16_off="n/a" tg_vs_f16_off="n/a"
            eval "p_on=\${mpp_${lvl}[\$mixed]:-}"
            eval "t_on=\${mtg_${lvl}[\$mixed]:-}"
            p_off="${mpp_scalar[$mixed]:-}"
            t_off="${mtg_scalar[$mixed]:-}"

            [ -n "$p_on" ] && [ -n "$f16_pp_on" ] && \
                pp_vs_f16_on=$(echo "$p_on $f16_pp_on" | awk '{if ($2 > 0) printf "%.2fx", $1/$2; else print "n/a"}')
            [ -n "$t_on" ] && [ -n "$f16_tg_on" ] && \
                tg_vs_f16_on=$(echo "$t_on $f16_tg_on" | awk '{if ($2 > 0) printf "%.2fx", $1/$2; else print "n/a"}')
            [ -n "$p_off" ] && [ -n "$f16_pp_off" ] && \
                pp_vs_f16_off=$(echo "$p_off $f16_pp_off" | awk '{if ($2 > 0) printf "%.2fx", $1/$2; else print "n/a"}')
            [ -n "$t_off" ] && [ -n "$f16_tg_off" ] && \
                tg_vs_f16_off=$(echo "$t_off $f16_tg_off" | awk '{if ($2 > 0) printf "%.2fx", $1/$2; else print "n/a"}')

            printf "  %-10s %-10s %12s %12s %12s %12s\n" \
                "$k_type" "$v_type" "$pp_vs_f16_on" "$pp_vs_f16_off" "$tg_vs_f16_on" "$tg_vs_f16_off"
        done

        echo "=========================================="
    }

    if [ "$SKIP_COOPMAT_COMPARE" != "1" ]; then
        for lvl in "${COOPMAT_LEVELS[@]}"; do
            print_mixed_table "$lvl"
            print_mixed_vs_f16_table "$lvl"
        done
    else
        echo ""
        echo "=========================================="
        echo " Mixed K/V Results [$cfg] (t/s, mean±stdev)"
        echo "=========================================="

        printf "  %-10s %-10s %16s %16s\n" "K type" "V type" "pp" "tg"
        printf "  %-10s %-10s %16s %16s\n" "------" "------" "--" "--"

        local f16_pp_s="${pp_scalar[f16]:-}"
        local f16_tg_s="${tg_scalar[f16]:-}"

        for mixed in "${MIXED_CONFIGS[@]}"; do
            k_type="${mixed%%:*}"
            v_type="${mixed##*:}"
            local pp_v="${mpp_scalar[$mixed]:-n/a}"
            local pp_sd="${mppsd_scalar[$mixed]:-}"
            local tg_v="${mtg_scalar[$mixed]:-n/a}"
            local tg_sd="${mtgsd_scalar[$mixed]:-}"
            local pp_d="$pp_v" tg_d="$tg_v"
            [ -n "$pp_sd" ] && [ "$pp_v" != "n/a" ] && pp_d="${pp_v}±${pp_sd}"
            [ -n "$tg_sd" ] && [ "$tg_v" != "n/a" ] && tg_d="${tg_v}±${tg_sd}"
            printf "  %-10s %-10s %16s %16s\n" "$k_type" "$v_type" "$pp_d" "$tg_d"
        done

        echo "=========================================="

        echo ""
        echo "=========================================="
        echo " Mixed K/V vs f16 Baseline [$cfg]"
        echo "=========================================="

        printf "  %-10s %-10s %12s %12s\n" "K type" "V type" "pp vs f16" "tg vs f16"
        printf "  %-10s %-10s %12s %12s\n" "------" "------" "---------" "---------"

        for mixed in "${MIXED_CONFIGS[@]}"; do
            k_type="${mixed%%:*}"
            v_type="${mixed##*:}"
            local pp_v="${mpp_scalar[$mixed]:-}"
            local tg_v="${mtg_scalar[$mixed]:-}"
            local pp_r="n/a" tg_r="n/a"
            [ -n "$pp_v" ] && [ -n "$f16_pp_s" ] && \
                pp_r=$(echo "$pp_v $f16_pp_s" | awk '{if ($2 > 0) printf "%.2fx", $1/$2; else print "n/a"}')
            [ -n "$tg_v" ] && [ -n "$f16_tg_s" ] && \
                tg_r=$(echo "$tg_v $f16_tg_s" | awk '{if ($2 > 0) printf "%.2fx", $1/$2; else print "n/a"}')
            printf "  %-10s %-10s %12s %12s\n" "$k_type" "$v_type" "$pp_r" "$tg_r"
        done

        echo "=========================================="
    fi

    # --- Write CSV rows with comparison columns ---

    if [ -n "$CSV_FILE" ]; then
        # Helper: compute ratio a/b, empty if b missing
        ratio() { echo "$1 $2" | awk '{if ($2 > 0) printf "%.2f", $1/$2; else print ""}'; }

        # Determine f16 baselines per coopmat level
        f16_pp_scalar="${pp_scalar[f16]:-}"
        f16_tg_scalar="${tg_scalar[f16]:-}"

        # Same-type: coopmat levels
        for lvl in "${COOPMAT_LEVELS[@]}"; do
            local_label=$(coopmat_label_for "$lvl")
            eval "f16_pp_lvl=\${pp_${lvl}[f16]:-}"
            eval "f16_tg_lvl=\${tg_${lvl}[f16]:-}"

            for cache_type in "${SAME_TYPE_CONFIGS[@]}"; do
                eval "pp_v=\${pp_${lvl}[$cache_type]:-}"
                eval "pp_sd_v=\${ppsd_${lvl}[$cache_type]:-}"
                eval "tg_v=\${tg_${lvl}[$cache_type]:-}"
                eval "tg_sd_v=\${tgsd_${lvl}[$cache_type]:-}"
                [ -z "$pp_v" ] && continue
                pp_vs_f16=$(ratio "$pp_v" "$f16_pp_lvl")
                tg_vs_f16=$(ratio "$tg_v" "$f16_tg_lvl")
                pp_vs_scl=$(ratio "$pp_v" "${pp_scalar[$cache_type]:-}")
                tg_vs_scl=$(ratio "$tg_v" "${tg_scalar[$cache_type]:-}")
                csv_append "$local_label" "$cache_type" "$cache_type" "no" "$PROMPT_LEN_CFG" "$GEN_LEN_CFG" \
                    "$pp_v" "$pp_sd_v" "$tg_v" "$tg_sd_v" "$cfg" "$REPS_CFG" \
                    "$pp_vs_f16" "$tg_vs_f16" "$pp_vs_scl" "$tg_vs_scl"
            done
        done

        # Same-type: scalar (when no coopmat or scalar baseline)
        if [ ${#COOPMAT_LEVELS[@]} -eq 0 ] || [ "$SKIP_COOPMAT_COMPARE" != "1" ]; then
            for cache_type in "${SAME_TYPE_CONFIGS[@]}"; do
                pp_v="${pp_scalar[$cache_type]:-}"
                pp_sd_v="${ppsd_scalar[$cache_type]:-}"
                tg_v="${tg_scalar[$cache_type]:-}"
                tg_sd_v="${tgsd_scalar[$cache_type]:-}"
                [ -z "$pp_v" ] && continue
                pp_vs_f16=$(ratio "$pp_v" "$f16_pp_scalar")
                tg_vs_f16=$(ratio "$tg_v" "$f16_tg_scalar")
                csv_append "scalar" "$cache_type" "$cache_type" "no" "$PROMPT_LEN_CFG" "$GEN_LEN_CFG" \
                    "$pp_v" "$pp_sd_v" "$tg_v" "$tg_sd_v" "$cfg" "$REPS_CFG" \
                    "$pp_vs_f16" "$tg_vs_f16" "" ""
            done
        fi

        # Mixed: coopmat levels
        for lvl in "${COOPMAT_LEVELS[@]}"; do
            local_label=$(coopmat_label_for "$lvl")
            eval "f16_pp_lvl=\${pp_${lvl}[f16]:-}"
            eval "f16_tg_lvl=\${tg_${lvl}[f16]:-}"

            for mixed in "${MIXED_CONFIGS[@]}"; do
                k_type="${mixed%%:*}"
                v_type="${mixed##*:}"
                eval "pp_v=\${mpp_${lvl}[$mixed]:-}"
                eval "pp_sd_v=\${mppsd_${lvl}[$mixed]:-}"
                eval "tg_v=\${mtg_${lvl}[$mixed]:-}"
                eval "tg_sd_v=\${mtgsd_${lvl}[$mixed]:-}"
                [ -z "$pp_v" ] && continue
                pp_vs_f16=$(ratio "$pp_v" "$f16_pp_lvl")
                tg_vs_f16=$(ratio "$tg_v" "$f16_tg_lvl")
                pp_vs_scl=$(ratio "$pp_v" "${mpp_scalar[$mixed]:-}")
                tg_vs_scl=$(ratio "$tg_v" "${mtg_scalar[$mixed]:-}")
                csv_append "$local_label" "$k_type" "$v_type" "yes" "$PROMPT_LEN_CFG" "$GEN_LEN_CFG" \
                    "$pp_v" "$pp_sd_v" "$tg_v" "$tg_sd_v" "$cfg" "$REPS_CFG" \
                    "$pp_vs_f16" "$tg_vs_f16" "$pp_vs_scl" "$tg_vs_scl"
            done
        done

        # Mixed: scalar
        if [ ${#COOPMAT_LEVELS[@]} -eq 0 ] || [ "$SKIP_COOPMAT_COMPARE" != "1" ]; then
            for mixed in "${MIXED_CONFIGS[@]}"; do
                k_type="${mixed%%:*}"
                v_type="${mixed##*:}"
                pp_v="${mpp_scalar[$mixed]:-}"
                pp_sd_v="${mppsd_scalar[$mixed]:-}"
                tg_v="${mtg_scalar[$mixed]:-}"
                tg_sd_v="${mtgsd_scalar[$mixed]:-}"
                [ -z "$pp_v" ] && continue
                pp_vs_f16=$(ratio "$pp_v" "$f16_pp_scalar")
                tg_vs_f16=$(ratio "$tg_v" "$f16_tg_scalar")
                csv_append "scalar" "$k_type" "$v_type" "yes" "$PROMPT_LEN_CFG" "$GEN_LEN_CFG" \
                    "$pp_v" "$pp_sd_v" "$tg_v" "$tg_sd_v" "$cfg" "$REPS_CFG" \
                    "$pp_vs_f16" "$tg_vs_f16" "" ""
            done
        fi
    fi

    # Clean up per-config associative arrays
    unset pp_scalar tg_scalar ppsd_scalar tgsd_scalar
    unset mpp_scalar mtg_scalar mppsd_scalar mtgsd_scalar
    for lvl in "${COOPMAT_LEVELS[@]}"; do
        unset "pp_${lvl}" "tg_${lvl}" "ppsd_${lvl}" "tgsd_${lvl}"
        unset "mpp_${lvl}" "mtg_${lvl}" "mppsd_${lvl}" "mtgsd_${lvl}"
    done

done  # end config loop

echo ""
echo "Done. Detected coopmat level: $COOPMAT_LEVEL."
echo "GPU device: $GPU_DEVICE"
if [ "$SKIP_COOPMAT_COMPARE" != "1" ]; then
    for lvl in "${COOPMAT_LEVELS[@]}"; do
        local_label=$(coopmat_label_for "$lvl")
        echo "Tables compare $local_label (prefill, N>1) vs scalar fallback."
    done
    echo "Speedup > 1.0x indicates coopmat benefit."
else
    echo "No coopmat comparison (either no coopmat support or SKIP_COOPMAT_COMPARE=1)."
fi
if [ -n "$CSV_FINAL" ]; then
    cp "$CSV_FILE" "$CSV_FINAL"
    rm -f "$CSV_FILE"
    echo "Results saved to: $CSV_FINAL (${#CSV_ROWS[@]} rows)"
    echo "Log saved to:     $LOG_FILE"
fi
