#!/usr/bin/env bash
#
# Test KV cache quantization quality via Needle-In-A-Haystack (NIAH) retrieval.
# Downloads a small model if not already present, then runs the passkey test
# across multiple cache types, haystack sizes and needle depths.
#
# Usage:
#   tests/test-kv-cache-quantization-niah.sh [options] [build_dir]
#
# Options:
#   -c <tiny|small|mid|large>  Size config preset (default: small)
#   --csv <file>               Write results to specific CSV file (auto-generated by default)
#
# Config presets (junk_sizes / depths / repeats):
#   tiny   — junk=250,             depths=0,50,100,        repeats=1  (smoke test)
#   small  — junk=250,500,         depths=0,50,100,        repeats=2  (quick)
#   mid    — junk=125,250,500,1000 depths=0,25,50,75,      repeats=2  (balanced)
#   large  — junk=125,250,500,1000 depths=0,25,50,75,100,  repeats=3  (thorough)
#
# Environment variables:
#   MODEL_DIR    — directory for model files (default: models)
#   MODEL_NAME   — GGUF filename
#   MODEL_URL    — download URL
#   CSV          — set to 0 to disable auto CSV output (default: 1)
#
# Examples:
#   tests/test-kv-cache-quantization-niah.sh -c small
#   tests/test-kv-cache-quantization-niah.sh -c large --csv niah.csv build
#
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

source "$SCRIPT_DIR/niah-bench.sh"

# --- Parse arguments ---

CONFIG="small"
CSV_FILE=""
BUILD_DIR=""

while [ $# -gt 0 ]; do
    case "$1" in
        -c)       shift; CONFIG="$1"; shift ;;
        --csv)    shift; CSV_FILE="$1"; shift ;;
        -h|--help) head -30 "$0" | tail -29; exit 0 ;;
        *)        BUILD_DIR="$1"; shift ;;
    esac
done

BUILD_DIR="${BUILD_DIR:-build}"
PASSKEY_BIN="$BUILD_DIR/bin/llama-passkey"

MODEL_DIR="${MODEL_DIR:-models}"
MODEL_NAME="${MODEL_NAME:-Mistral-7B-Instruct-v0.3-Q4_K_S.gguf}"
MODEL_URL="${MODEL_URL:-https://huggingface.co/bartowski/Mistral-7B-Instruct-v0.3-GGUF/resolve/main/Mistral-7B-Instruct-v0.3-Q4_K_S.gguf}"
MODEL_PATH="$MODEL_DIR/$MODEL_NAME"

# --- Config presets ---

config_junk_sizes() {
    case "$1" in
        tiny)  echo "250" ;;
        small) echo "250 500" ;;
        mid)   echo "125 250 500 1000" ;;
        large) echo "125 250 500 1000" ;;
        *) echo "Error: unknown config '$1' (expected tiny, small, mid, large)" >&2; exit 1 ;;
    esac
}

config_depths() {
    case "$1" in
        tiny)  echo "0 50 100" ;;
        small) echo "0 50 100" ;;
        mid)   echo "0 25 50 75" ;;
        large) echo "0 25 50 75 100" ;;
        *) echo "Error: unknown config '$1'" >&2; exit 1 ;;
    esac
}

config_repeats() {
    case "$1" in
        tiny)  echo 1 ;;
        small) echo 2 ;;
        mid)   echo 2 ;;
        large) echo 3 ;;
        *) echo "Error: unknown config '$1'" >&2; exit 1 ;;
    esac
}

JUNK_SIZES=$(config_junk_sizes "$CONFIG")
DEPTHS=$(config_depths "$CONFIG")
REPEATS=$(config_repeats "$CONFIG")

CACHE_TYPES=("tbq3_0" "q4_0" "pq3_0" "tbq4_0" "f16" "q8_0" "pq4_0")

# --- Download dependencies ---

if [ ! -x "$PASSKEY_BIN" ]; then
    echo "Error: $PASSKEY_BIN not found. Build the project first."
    echo "  cmake -B $BUILD_DIR && cmake --build $BUILD_DIR --target llama-passkey -j\$(nproc)"
    exit 1
fi

mkdir -p "$MODEL_DIR"

if [ ! -f "$MODEL_PATH" ] || [ "$(stat -c%s "$MODEL_PATH" 2>/dev/null || echo 0)" -lt 1000000 ]; then
    [ -f "$MODEL_PATH" ] && rm -f "$MODEL_PATH"
    echo "Downloading model: $MODEL_NAME ..."
    if command -v curl &> /dev/null; then
        curl -L --fail -C - -o "$MODEL_PATH" "$MODEL_URL"
    elif command -v wget &> /dev/null; then
        wget -O "$MODEL_PATH" "$MODEL_URL"
    else
        echo "Error: neither curl nor wget found"
        exit 1
    fi

    FILE_SIZE=$(stat -c%s "$MODEL_PATH" 2>/dev/null || echo 0)
    if [ "$FILE_SIZE" -lt 1000000 ]; then
        echo "Error: downloaded file is only $FILE_SIZE bytes — likely a redirect or error page."
        rm -f "$MODEL_PATH"
        exit 1
    fi
    echo "Model downloaded to $MODEL_PATH ($((FILE_SIZE / 1048576)) MB)"
else
    echo "Model already exists: $MODEL_PATH"
fi

# --- GPU device detection ---

detect_gpu_device() {
    local gpu_info=""
    local bench_bin="$BUILD_DIR/bin/llama-bench"

    if [ -f "$bench_bin" ]; then
        gpu_info=$("$bench_bin" --list-devices 2>&1 | grep -E '^\s+(Vulkan|CUDA|Metal|SYCL|ROCm)' | head -1 | sed 's/^[[:space:]]*//' || true)
    fi

    if [ -z "$gpu_info" ]; then
        if command -v nvidia-smi &> /dev/null; then
            gpu_info=$(nvidia-smi --query-gpu=name --format=csv,noheader 2>/dev/null | head -1 || true)
        elif command -v vulkaninfo &> /dev/null; then
            gpu_info=$(vulkaninfo 2>/dev/null | grep "deviceName" | head -1 | sed 's/.*= //' || true)
        fi
    fi

    echo "${gpu_info:-unknown}"
}

GPU_DEVICE=$(detect_gpu_device)

# --- Bits per value ---

get_bpw() {
    case "$1" in
        f16)     echo "16.00" ;;
        q8_0)    echo "8.50"  ;;
        q4_0)    echo "4.50"  ;;
        q4_1)    echo "5.00"  ;;
        pq3_0)   echo "3.25"  ;;
        pq4_0)   echo "4.25"  ;;
        tbq3_0)  echo "4.25"  ;;
        tbq4_0)  echo "5.25"  ;;
        *)       echo "0.00"  ;;
    esac
}

# --- Auto-generate CSV/log filenames ---

CSV_FINAL=""
if [ -z "$CSV_FILE" ] && [ "${CSV:-1}" != "0" ]; then
    sanitize() { echo "$1" | tr '[:upper:]' '[:lower:]' | sed 's/[^a-z0-9._-]/_/g; s/__*/_/g; s/^_//; s/_$//'; }
    GPU_SHORT=$(echo "$GPU_DEVICE" | sed 's/^[A-Za-z]*[0-9]*: //; s/ ([0-9].*//')
    GPU_TAG=$(sanitize "$GPU_SHORT")
    MODEL_TAG=$(sanitize "${MODEL_NAME%.gguf}")
    CSV_FILE="kv-niah_${GPU_TAG}_${MODEL_TAG}_${CONFIG}_$(date +%Y%m%d_%H%M%S).csv"
fi
if [ -n "$CSV_FILE" ]; then
    CSV_FINAL="$CSV_FILE"
    CSV_FILE=$(mktemp /tmp/kv-niah-XXXXXX.csv)
fi

LOG_FILE=""
if [ -n "$CSV_FINAL" ]; then
    LOG_FILE="${CSV_FINAL%.csv}.txt"
    exec > >(tee -a "$LOG_FILE") 2>&1
fi

# --- CSV setup ---

CSV_ROWS=()

csv_init() {
    if [ -n "$CSV_FILE" ]; then
        echo "gpu_device,model,config,cache_type,bpw,junk_sizes,depths,repeats,global_acc_pct,global_acc_stdev,global_pass,global_total,cell_mean_pct,cell_stdev_pct,n_cells" > "$CSV_FILE"
    fi
}

csv_append() {
    local cache_type="$1" bpw="$2"
    local row="\"$GPU_DEVICE\",\"$MODEL_NAME\",\"$CONFIG\",\"$cache_type\",$bpw,\"$JUNK_SIZES\",\"$DEPTHS\",$REPEATS,$niah_global_pct,$niah_global_stdev,$niah_global_pass,$niah_global_total,$niah_cell_mean,$niah_cell_stdev,$niah_n_cells"
    CSV_ROWS+=("$row")
    if [ -n "$CSV_FILE" ]; then
        echo "$row" >> "$CSV_FILE"
    fi
}

csv_init

# --- Print header ---

echo ""
echo "=========================================="
echo " KV Cache Quantization NIAH Test"
echo "=========================================="
echo " GPU:      $GPU_DEVICE"
echo " Model:    $MODEL_NAME"
echo " Config:   $CONFIG (junk=[$JUNK_SIZES] depths=[$DEPTHS] repeats=$REPEATS)"
if [ -n "$CSV_FINAL" ]; then
    echo " CSV:      $CSV_FINAL"
    echo " Log:      $LOG_FILE"
fi
echo "=========================================="
echo ""

# --- Main benchmark loop ---

declare -A res_global_pct res_global_stdev res_global_pass res_global_total
declare -A res_cell_mean res_cell_stdev res_n_cells

for cache_type in "${CACHE_TYPES[@]}"; do
    bpw=$(get_bpw "$cache_type")
    echo ""
    echo "--- Running NIAH with K=$cache_type V=$cache_type (BPW=$bpw) ---"
    echo ""

    niah_bench \
        -m "$MODEL_PATH" \
        -ctk "$cache_type" -ctv "$cache_type" \
        --junk-sizes "$JUNK_SIZES" \
        --depths "$DEPTHS" \
        --repeats "$REPEATS" \
        --passkey-bin "$PASSKEY_BIN"

    res_global_pct["$cache_type"]=$niah_global_pct
    res_global_stdev["$cache_type"]=$niah_global_stdev
    res_global_pass["$cache_type"]=$niah_global_pass
    res_global_total["$cache_type"]=$niah_global_total
    res_cell_mean["$cache_type"]=$niah_cell_mean
    res_cell_stdev["$cache_type"]=$niah_cell_stdev
    res_n_cells["$cache_type"]=$niah_n_cells

    csv_append "$cache_type" "$bpw"

    echo ""
done

# --- Summary table ---

echo ""
echo "=========================================="
echo " Results Summary [$CONFIG]"
echo "=========================================="
printf "  %-14s %-6s %18s %18s %12s\n" "Type" "BPW" "Global Acc" "Cell Uniformity" "Trials"
printf "  %-14s %-6s %18s %18s %12s\n" "----" "---" "----------" "---------------" "------"

baseline_pct="${res_global_pct[f16]}"

for cache_type in "${CACHE_TYPES[@]}"; do
    bpw=$(get_bpw "$cache_type")
    g_pct="${res_global_pct[$cache_type]}"
    g_sd="${res_global_stdev[$cache_type]}"
    c_mean="${res_cell_mean[$cache_type]}"
    c_sd="${res_cell_stdev[$cache_type]}"
    g_pass="${res_global_pass[$cache_type]}"
    g_total="${res_global_total[$cache_type]}"

    acc_disp="${g_pct} ± ${g_sd}%"
    cell_disp="${c_mean} ± ${c_sd}%"
    trials_disp="${g_pass}/${g_total}"

    if [ "$cache_type" = "f16" ]; then
        printf "  %-14s %-6s %18s %18s %12s  (baseline)\n" "$cache_type" "$bpw" "$acc_disp" "$cell_disp" "$trials_disp"
    else
        delta=$(awk "BEGIN { printf \"%+.1f\", $g_pct - $baseline_pct }")
        printf "  %-14s %-6s %18s %18s %12s  (%s%%)\n" "$cache_type" "$bpw" "$acc_disp" "$cell_disp" "$trials_disp" "$delta"
    fi
done

echo "=========================================="

# --- Regression checks ---

num_failed=0
for cache_type in "${CACHE_TYPES[@]}"; do
    [ "$cache_type" = "f16" ] && continue
    g_pct="${res_global_pct[$cache_type]}"
    failed=$(awk "BEGIN { print ($g_pct < $baseline_pct - 20) ? 1 : 0 }")
    if [ "$failed" = "1" ]; then
        echo "FAILED: $cache_type accuracy ${g_pct}% is >20 points below f16 baseline ${baseline_pct}%"
        num_failed=$((num_failed + 1))
    fi
done

echo ""
echo "GPU device: $GPU_DEVICE"
if [ "$num_failed" -eq 0 ]; then
    echo "All checks passed."
else
    echo "$num_failed check(s) failed."
fi
if [ -n "$CSV_FINAL" ]; then
    cp "$CSV_FILE" "$CSV_FINAL"
    rm -f "$CSV_FILE"
    echo "Results saved to: $CSV_FINAL (${#CSV_ROWS[@]} rows)"
    echo "Log saved to:     $LOG_FILE"
fi
