#!/usr/bin/env bash
#
# Test KV cache quantization quality via KL Divergence against f16 baseline.
# Two-step process: save f16 logits, then compare each quantized cache type.
#
# Why KLD for KV cache quantization:
#   KLD measures distributional shift at the output level. Unlike PPL (which
#   can accidentally improve due to quantization noise acting as regularization),
#   KLD detects any deviation from f16 behavior — even when the model still
#   picks the "correct" top token.
#
# Why long context matters (QJL / TurboQuant):
#   TurboQuant's QJL correction provides *unbiased* inner-product estimation
#   for attention scores (Q·K). The benefit of unbiasedness is that errors
#   don't accumulate systematically over long contexts. However:
#
#   - The TurboQuant paper demonstrated perfect NIAH retrieval up to 104K
#     tokens, and tested KV quality at up to 128K context.
#   - Community implementations report that QJL's practical benefit over
#     MSE-only (PolarQuant) is small at short/medium contexts (<8K).
#   - llama-perplexity evaluates only the *second half* of each chunk
#     (positions n_ctx/2 .. n_ctx), which naturally emphasizes tokens that
#     depend on long-range attention. At 32K context (huge preset), this
#     means evaluating positions 16K–32K where accumulated bias from
#     non-QJL quantization should be most visible.
#
#   Use the 'huge' preset (32K context) for a definitive QJL comparison.
#   Smaller presets are useful for quick quality checks but may not show
#   QJL's unbiasedness benefit.
#
# Metrics reported per cache type:
#   Mean KLD          — KL divergence (lower = closer to f16, 0 = identical)
#   Δp RMS            — RMS of token-probability difference (lower = better)
#   Same top p        — % of tokens where top prediction matches f16
#   PPL(Q)            — perplexity of the quantized model
#   PPL(base)         — perplexity of the f16 baseline (constant across types)
#   ln(PPL(Q)/PPL(base)) — log ratio (positive = worse, 0 = identical)
#
# Usage:
#   tests/test-kv-cache-quantization-kld.sh [options] [build_dir]
#
# Options:
#   -c <tiny|small|mid|large|huge>  Size config preset (default: small)
#   --csv <file>                    Write results to specific CSV file (auto-generated by default)
#
# Config presets (n_chunks / n_ctx) — tuned for Llama-3.1-8B (128K context):
#   tiny   — 1 chunk,  n_ctx 2K         (smoke test)
#   small  — 2 chunks, n_ctx 4K         (quick)
#   mid    — 1 chunk,  n_ctx 8K         (moderate)
#   large  — 1 chunk,  n_ctx 12K        (long-context)
#   huge   — 1 chunk,  n_ctx 16K        (longest feasible with --save-all-logits)
#
# Note: --save-all-logits allocates n_ctx × (n_vocab+2) × 2 bytes in RAM.
# With Llama-3.1's 128K vocab: 16K ctx ≈ 4 GB, 32K ctx ≈ 8 GB (crashes).
# This is a hard limit of llama-perplexity's logit-saving mechanism.
#
# Environment variables:
#   MODEL_DIR    — directory for model files (default: models)
#   MODEL_NAME   — GGUF filename
#   MODEL_URL    — download URL
#   CSV          — set to 0 to disable auto CSV output (default: 1)
#
# Examples:
#   tests/test-kv-cache-quantization-kld.sh -c small
#   tests/test-kv-cache-quantization-kld.sh -c huge --csv kld_32k.csv build
#
set -euo pipefail

# --- Parse arguments ---

CONFIG="small"
CSV_FILE=""
BUILD_DIR=""

while [ $# -gt 0 ]; do
    case "$1" in
        -c)       shift; CONFIG="$1"; shift ;;
        --csv)    shift; CSV_FILE="$1"; shift ;;
        -h|--help) head -58 "$0" | tail -57; exit 0 ;;
        *)        BUILD_DIR="$1"; shift ;;
    esac
done

BUILD_DIR="${BUILD_DIR:-build}"
PERPLEXITY="$BUILD_DIR/bin/llama-perplexity"

MODEL_DIR="${MODEL_DIR:-models}"
# Llama-3.1-8B-Instruct: 128K training context — required for testing QJL
# unbiasedness at long range. The TurboQuant paper showed QJL's benefit at
# 100K+ context; Mistral-7B (32K max) is too short to observe the effect.
MODEL_NAME="${MODEL_NAME:-Meta-Llama-3.1-8B-Instruct-Q4_K_S.gguf}"
MODEL_URL="${MODEL_URL:-https://huggingface.co/bartowski/Meta-Llama-3.1-8B-Instruct-GGUF/resolve/main/Meta-Llama-3.1-8B-Instruct-Q4_K_S.gguf}"
# Mistral-7B-Instruct-v0.3 (32K context — too short for QJL comparison):
# MODEL_NAME="${MODEL_NAME:-Mistral-7B-Instruct-v0.3-Q4_K_S.gguf}"
# MODEL_URL="${MODEL_URL:-https://huggingface.co/bartowski/Mistral-7B-Instruct-v0.3-GGUF/resolve/main/Mistral-7B-Instruct-v0.3-Q4_K_S.gguf}"
MODEL_PATH="$MODEL_DIR/$MODEL_NAME"

DATASET_DIR="wikitext-2-raw"
DATASET_FILE="$DATASET_DIR/wiki.test.raw"
DATASET_ZIP="wikitext-2-raw-v1.zip"
DATASET_URL="https://huggingface.co/datasets/ggml-org/ci/resolve/main/$DATASET_ZIP"

CACHE_TYPES=("tbq3_0" "q4_0" "pq3_0" "tbq4_0" "q8_0" "pq4_0")

is_tq_type() {
    case "$1" in
        tbq3_0|tbq4_0|pq3_0|pq4_0) return 0 ;;
        *) return 1 ;;
    esac
}

# --- Config presets ---

config_n_chunks() {
    case "$1" in
        tiny)  echo 1 ;;
        small) echo 2 ;;
        mid)   echo 1 ;;
        large) echo 1 ;;
        huge)  echo 1 ;;
        *) echo "Error: unknown config '$1' (expected tiny, small, mid, large, huge)" >&2; exit 1 ;;
    esac
}

# n_ctx is limited by --save-all-logits memory: n_ctx × n_vocab × 2 bytes.
# For Llama-3.1 (128K vocab): 16K ctx ≈ 4 GB, 32K ctx ≈ 8 GB logits file.
# Beyond ~32K the logits buffer exceeds typical RAM limits.
config_n_ctx() {
    case "$1" in
        tiny)  echo 2048 ;;
        small) echo 4096 ;;
        mid)   echo 8192 ;;
        large) echo 12288 ;;
        huge)  echo 16384 ;;
        *) echo "Error: unknown config '$1'" >&2; exit 1 ;;
    esac
}

N_CHUNKS=$(config_n_chunks "$CONFIG")
N_CTX=$(config_n_ctx "$CONFIG")

# --- Download dependencies ---

if [ ! -f "$PERPLEXITY" ]; then
    echo "Error: $PERPLEXITY not found. Build the project first."
    echo "  cmake -B $BUILD_DIR && cmake --build $BUILD_DIR -j\$(nproc)"
    exit 1
fi

mkdir -p "$MODEL_DIR"

if [ ! -f "$MODEL_PATH" ] || [ "$(stat -c%s "$MODEL_PATH" 2>/dev/null || echo 0)" -lt 1000000 ]; then
    [ -f "$MODEL_PATH" ] && rm -f "$MODEL_PATH"
    echo "Downloading model: $MODEL_NAME ..."
    if command -v curl &> /dev/null; then
        curl -L --fail -C - -o "$MODEL_PATH" "$MODEL_URL"
    elif command -v wget &> /dev/null; then
        wget -O "$MODEL_PATH" "$MODEL_URL"
    else
        echo "Error: neither curl nor wget found"
        exit 1
    fi

    FILE_SIZE=$(stat -c%s "$MODEL_PATH" 2>/dev/null || echo 0)
    if [ "$FILE_SIZE" -lt 1000000 ]; then
        echo "Error: downloaded file is only $FILE_SIZE bytes — likely a redirect or error page."
        rm -f "$MODEL_PATH"
        exit 1
    fi
    echo "Model downloaded to $MODEL_PATH ($((FILE_SIZE / 1048576)) MB)"
else
    echo "Model already exists: $MODEL_PATH"
fi

if [ ! -f "$DATASET_FILE" ]; then
    echo "Downloading wikitext-2 dataset..."
    if command -v curl &> /dev/null; then
        curl -L -o "$DATASET_ZIP" "$DATASET_URL"
    elif command -v wget &> /dev/null; then
        wget -O "$DATASET_ZIP" "$DATASET_URL"
    else
        echo "Error: neither curl nor wget found"
        exit 1
    fi
    unzip -o "$DATASET_ZIP"
    rm -f "$DATASET_ZIP"
    echo "Dataset extracted to $DATASET_DIR"
else
    echo "Dataset already exists: $DATASET_FILE"
fi

# --- GPU device detection ---

detect_gpu_device() {
    local gpu_info=""
    local bench_bin="$BUILD_DIR/bin/llama-bench"

    if [ -f "$bench_bin" ]; then
        gpu_info=$("$bench_bin" --list-devices 2>&1 | grep -E '^\s+(Vulkan|CUDA|Metal|SYCL|ROCm)' | head -1 | sed 's/^[[:space:]]*//' || true)
    fi

    if [ -z "$gpu_info" ]; then
        if command -v nvidia-smi &> /dev/null; then
            gpu_info=$(nvidia-smi --query-gpu=name --format=csv,noheader 2>/dev/null | head -1 || true)
        elif command -v vulkaninfo &> /dev/null; then
            gpu_info=$(vulkaninfo 2>/dev/null | grep "deviceName" | head -1 | sed 's/.*= //' || true)
        fi
    fi

    echo "${gpu_info:-unknown}"
}

GPU_DEVICE=$(detect_gpu_device)

# --- Bits per value ---

get_bpw() {
    case "$1" in
        f16)     echo "16.00" ;;
        q8_0)    echo "8.50"  ;;
        q4_0)    echo "4.50"  ;;
        q4_1)    echo "5.00"  ;;
        pq3_0)   echo "3.25"  ;;
        pq4_0)   echo "4.25"  ;;
        tbq3_0)  echo "4.25"  ;;
        tbq4_0)  echo "5.25"  ;;
        *)       echo "0.00"  ;;
    esac
}

# --- Auto-generate CSV/log filenames ---

CSV_FINAL=""
if [ -z "$CSV_FILE" ] && [ "${CSV:-1}" != "0" ]; then
    sanitize() { echo "$1" | tr '[:upper:]' '[:lower:]' | sed 's/[^a-z0-9._-]/_/g; s/__*/_/g; s/^_//; s/_$//'; }
    GPU_SHORT=$(echo "$GPU_DEVICE" | sed 's/^[A-Za-z]*[0-9]*: //; s/ ([0-9].*//')
    GPU_TAG=$(sanitize "$GPU_SHORT")
    MODEL_TAG=$(sanitize "${MODEL_NAME%.gguf}")
    CSV_FILE="kv-kld_${GPU_TAG}_${MODEL_TAG}_${CONFIG}_$(date +%Y%m%d_%H%M%S).csv"
fi
if [ -n "$CSV_FILE" ]; then
    CSV_FINAL="$CSV_FILE"
    CSV_FILE=$(mktemp /tmp/kv-kld-XXXXXX.csv)
fi

LOG_FILE=""
if [ -n "$CSV_FINAL" ]; then
    LOG_FILE="${CSV_FINAL%.csv}.txt"
    exec > >(tee -a "$LOG_FILE") 2>&1
fi

# --- CSV setup ---

CSV_ROWS=()

NC_FLAG="off"

csv_init() {
    if [ -n "$CSV_FILE" ]; then
        echo "gpu_device,model,config,cache_type,norm_correction,bpw,n_chunks,n_ctx,mean_kld,mean_kld_unc,delta_p_rms,delta_p_rms_unc,same_top_p,same_top_p_unc,ppl_q,ppl_q_unc,ppl_base,ppl_base_unc,ln_ppl_ratio,ln_ppl_ratio_unc,time_s" > "$CSV_FILE"
    fi
}

csv_append() {
    local cache_type="$1" bpw="$2" time_s="$3"
    local row="\"$GPU_DEVICE\",\"$MODEL_NAME\",\"$CONFIG\",\"$cache_type\",\"$NC_FLAG\",$bpw,$N_CHUNKS,$N_CTX"
    row+=",$kld_mean,$kld_mean_unc,$dp_rms,$dp_rms_unc,$same_top,$same_top_unc"
    row+=",$ppl_q,$ppl_q_unc,$ppl_base,$ppl_base_unc,$ln_ppl_ratio,$ln_ppl_ratio_unc,$time_s"
    CSV_ROWS+=("$row")
    if [ -n "$CSV_FILE" ]; then
        echo "$row" >> "$CSV_FILE"
    fi
}

csv_init

# --- Print header ---

echo ""
echo "=========================================="
echo " KV Cache Quantization KL Divergence Test"
echo "=========================================="
echo " GPU:      $GPU_DEVICE"
echo " Model:    $MODEL_NAME"
echo " Dataset:  $DATASET_FILE"
echo " Config:   $CONFIG (chunks=$N_CHUNKS, n_ctx=$N_CTX)"
if [ -n "$CSV_FINAL" ]; then
    echo " CSV:      $CSV_FINAL"
    echo " Log:      $LOG_FILE"
fi
echo "=========================================="
echo ""

# --- Step 1: Generate f16 baseline logits ---

LOGITS_FILE=$(mktemp /tmp/kv-kld-logits-XXXXXX.bin)

echo "--- Step 1: Saving f16 baseline logits ---"
echo "  Logits file: $LOGITS_FILE"
echo ""

start_time=$(date +%s%N)

# Use -c (--ctx-size) not -n (--predict) — llama-perplexity uses -c for
# the context window and ignores -n. Also set -b (batch size) equal to
# the context size so llama-perplexity computes n_seq = n_batch / n_ctx = 1,
# ensuring the full context window is used as a single long sequence.
# This is required to measure long-context effects like QJL unbiasedness.
"$PERPLEXITY" \
    -m "$MODEL_PATH" \
    -f "$DATASET_FILE" \
    --cache-type-k "f16" --cache-type-v "f16" \
    -c "$N_CTX" -b "$N_CTX" \
    --chunks "$N_CHUNKS" \
    --save-all-logits "$LOGITS_FILE" \
    2>&1 | tee /dev/stderr | tail -5

end_time=$(date +%s%N)
baseline_time_s=$(echo "$(( (end_time - start_time) / 1000000 ))" | awk '{printf "%.1f", $1/1000}')

echo ""
echo "  f16 baseline logits saved (${baseline_time_s}s)"
echo ""

# --- Step 2: Run KLD for each quantized cache type ---

# Result storage
declare -A res_kld_mean res_kld_mean_unc
declare -A res_dp_rms res_dp_rms_unc
declare -A res_same_top res_same_top_unc
declare -A res_ppl_q res_ppl_q_unc
declare -A res_ppl_base res_ppl_base_unc
declare -A res_ln_ratio res_ln_ratio_unc
declare -A res_time_s

extract_kld_metrics() {
    local output="$1"

    kld_mean=$(echo "$output" | grep -oP 'Mean    KLD:\s*\K[0-9]+\.[0-9]+' | head -1)
    kld_mean_unc=$(echo "$output" | grep 'Mean    KLD:' | grep -oP '±\s*\K[0-9]+\.[0-9]+' | head -1)

    dp_rms=$(echo "$output" | grep 'RMS Δp' | grep -oP ':\s*\K[0-9]+\.[0-9]+' | head -1)
    dp_rms_unc=$(echo "$output" | grep 'RMS Δp' | grep -oP '±\s*\K[0-9]+\.[0-9]+' | head -1)

    same_top=$(echo "$output" | grep 'Same top p' | grep -oP ':\s*\K[0-9]+\.[0-9]+' | head -1)
    same_top_unc=$(echo "$output" | grep 'Same top p' | grep -oP '±\s*\K[0-9]+\.[0-9]+' | head -1)

    ppl_q=$(echo "$output" | grep 'Mean PPL(Q)' | grep -oP ':\s*\K[0-9]+\.[0-9]+' | head -1)
    ppl_q_unc=$(echo "$output" | grep 'Mean PPL(Q)' | grep -oP '±\s*\K[0-9]+\.[0-9]+' | head -1)

    ppl_base=$(echo "$output" | grep 'Mean PPL(base)' | grep -oP ':\s*\K[0-9]+\.[0-9]+' | head -1)
    ppl_base_unc=$(echo "$output" | grep 'Mean PPL(base)' | grep -oP '±\s*\K[0-9]+\.[0-9]+' | head -1)

    ln_ppl_ratio=$(echo "$output" | grep 'Mean ln(PPL(Q)/PPL(base))' | grep -oP ':\s*\K-?[0-9]+\.[0-9]+' | head -1)
    ln_ppl_ratio_unc=$(echo "$output" | grep 'Mean ln(PPL(Q)/PPL(base))' | grep -oP '±\s*\K[0-9]+\.[0-9]+' | head -1)

    # Defaults for missing values
    kld_mean="${kld_mean:-}"
    kld_mean_unc="${kld_mean_unc:-}"
    dp_rms="${dp_rms:-}"
    dp_rms_unc="${dp_rms_unc:-}"
    same_top="${same_top:-}"
    same_top_unc="${same_top_unc:-}"
    ppl_q="${ppl_q:-}"
    ppl_q_unc="${ppl_q_unc:-}"
    ppl_base="${ppl_base:-}"
    ppl_base_unc="${ppl_base_unc:-}"
    ln_ppl_ratio="${ln_ppl_ratio:-}"
    ln_ppl_ratio_unc="${ln_ppl_ratio_unc:-}"
}

# Alpha-scaled result storage
declare -A res_kld_mean_a res_kld_mean_unc_a
declare -A res_dp_rms_a res_dp_rms_unc_a
declare -A res_same_top_a res_same_top_unc_a
declare -A res_ppl_q_a res_ppl_q_unc_a
declare -A res_ln_ratio_a res_ln_ratio_unc_a
declare -A res_time_s_a

run_kld_once() {
    local cache_type="$1" label="$2"
    local bpw
    bpw=$(get_bpw "$cache_type")
    echo "--- Running KLD: K=$cache_type V=$cache_type ($label, BPW=$bpw) ---"
    echo ""

    local start_time end_time elapsed_s kld_output
    start_time=$(date +%s%N)

    # -c (not -n) for context size; -b = ctx to force n_seq=1 (see baseline comment)
    kld_output=$("$PERPLEXITY" \
        -m "$MODEL_PATH" \
        -f "$DATASET_FILE" \
        --cache-type-k "$cache_type" --cache-type-v "$cache_type" \
        -c "$N_CTX" -b "$N_CTX" \
        --chunks "$N_CHUNKS" \
        --kl-divergence --kl-divergence-base "$LOGITS_FILE" \
        2>&1) || true

    end_time=$(date +%s%N)
    elapsed_s=$(echo "$(( (end_time - start_time) / 1000000 ))" | awk '{printf "%.1f", $1/1000}')

    echo "$kld_output" | grep -E 'Mean KLD|RMS|Same top|Mean PPL|Mean ln' || true
    echo "  Time: ${elapsed_s}s"
    echo ""

    extract_kld_metrics "$kld_output"
    _last_elapsed_s="$elapsed_s"
}

export GGML_TQ_NORM_CORRECTION=0

for cache_type in "${CACHE_TYPES[@]}"; do
    run_kld_once "$cache_type" "standard"

    res_kld_mean["$cache_type"]="$kld_mean"
    res_kld_mean_unc["$cache_type"]="$kld_mean_unc"
    res_dp_rms["$cache_type"]="$dp_rms"
    res_dp_rms_unc["$cache_type"]="$dp_rms_unc"
    res_same_top["$cache_type"]="$same_top"
    res_same_top_unc["$cache_type"]="$same_top_unc"
    res_ppl_q["$cache_type"]="$ppl_q"
    res_ppl_q_unc["$cache_type"]="$ppl_q_unc"
    res_ppl_base["$cache_type"]="$ppl_base"
    res_ppl_base_unc["$cache_type"]="$ppl_base_unc"
    res_ln_ratio["$cache_type"]="$ln_ppl_ratio"
    res_ln_ratio_unc["$cache_type"]="$ln_ppl_ratio_unc"
    res_time_s["$cache_type"]="$_last_elapsed_s"

    csv_append "$cache_type" "$(get_bpw "$cache_type")" "$_last_elapsed_s"

    if is_tq_type "$cache_type"; then
        export GGML_TQ_NORM_CORRECTION=1
        run_kld_once "$cache_type" "α-scaled"
        export GGML_TQ_NORM_CORRECTION=0

        res_kld_mean_a["$cache_type"]="$kld_mean"
        res_kld_mean_unc_a["$cache_type"]="$kld_mean_unc"
        res_dp_rms_a["$cache_type"]="$dp_rms"
        res_dp_rms_unc_a["$cache_type"]="$dp_rms_unc"
        res_same_top_a["$cache_type"]="$same_top"
        res_same_top_unc_a["$cache_type"]="$same_top_unc"
        res_ppl_q_a["$cache_type"]="$ppl_q"
        res_ppl_q_unc_a["$cache_type"]="$ppl_q_unc"
        res_ln_ratio_a["$cache_type"]="$ln_ppl_ratio"
        res_ln_ratio_unc_a["$cache_type"]="$ln_ppl_ratio_unc"
        res_time_s_a["$cache_type"]="$_last_elapsed_s"

        NC_FLAG="on"
        csv_append "$cache_type" "$(get_bpw "$cache_type")" "$_last_elapsed_s"
        NC_FLAG="off"
    fi
done

# --- Cleanup logits file ---

rm -f "$LOGITS_FILE"

# --- Summary table ---

echo ""
echo "=========================================="
echo " KL Divergence Results Summary [$CONFIG]"
echo "=========================================="
echo ""
printf "  %-14s %-6s %18s %14s %14s %22s %10s\n" \
    "Type" "BPW" "Mean KLD" "Δp RMS" "Same top p" "ln(PPL(Q)/PPL(base))" "Time"
printf "  %-14s %-6s %18s %14s %14s %22s %10s\n" \
    "----" "---" "--------" "------" "----------" "--------------------" "----"

fmt_kld_row() {
    local label="$1" bpw="$2" kld="$3" kld_u="$4" dp="$5" dp_u="$6"
    local st="$7" st_u="$8" lr="$9" lr_u="${10}" ts="${11}"

    local kld_disp="$kld" dp_disp="$dp" st_disp="$st" lr_disp="$lr"
    [ -n "$kld_u" ] && kld_disp="${kld}±${kld_u}"
    [ -n "$dp_u" ] && dp_disp="${dp}±${dp_u}%"
    [ -n "$st_u" ] && st_disp="${st}±${st_u}%"
    [ -n "$lr_u" ] && lr_disp="${lr}±${lr_u}"

    printf "  %-14s %-6s %18s %14s %14s %22s %9ss\n" \
        "$label" "$bpw" "$kld_disp" "$dp_disp" "$st_disp" "$lr_disp" "$ts"
}

for cache_type in "${CACHE_TYPES[@]}"; do
    bpw=$(get_bpw "$cache_type")
    fmt_kld_row "$cache_type" "$bpw" \
        "${res_kld_mean[$cache_type]:-n/a}" "${res_kld_mean_unc[$cache_type]:-}" \
        "${res_dp_rms[$cache_type]:-n/a}" "${res_dp_rms_unc[$cache_type]:-}" \
        "${res_same_top[$cache_type]:-n/a}" "${res_same_top_unc[$cache_type]:-}" \
        "${res_ln_ratio[$cache_type]:-n/a}" "${res_ln_ratio_unc[$cache_type]:-}" \
        "${res_time_s[$cache_type]:-}"

    if [ -n "${res_kld_mean_a[$cache_type]:-}" ]; then
        fmt_kld_row "  └ α" "-" \
            "${res_kld_mean_a[$cache_type]:-n/a}" "${res_kld_mean_unc_a[$cache_type]:-}" \
            "${res_dp_rms_a[$cache_type]:-n/a}" "${res_dp_rms_unc_a[$cache_type]:-}" \
            "${res_same_top_a[$cache_type]:-n/a}" "${res_same_top_unc_a[$cache_type]:-}" \
            "${res_ln_ratio_a[$cache_type]:-n/a}" "${res_ln_ratio_unc_a[$cache_type]:-}" \
            "${res_time_s_a[$cache_type]:-}"
    fi
done

echo ""

# PPL(base) is constant across types; show it once
first_type="${CACHE_TYPES[0]}"
echo "  PPL(base) = ${res_ppl_base[$first_type]:-n/a} ± ${res_ppl_base_unc[$first_type]:-n/a}  (f16 baseline)"
echo ""

# Per-type PPL(Q) comparison
printf "  %-14s %-6s %18s %18s\n" "Type" "BPW" "PPL(Q)" "PPL(Q)/PPL(base)"
printf "  %-14s %-6s %18s %18s\n" "----" "---" "------" "----------------"

for cache_type in "${CACHE_TYPES[@]}"; do
    bpw=$(get_bpw "$cache_type")
    pq="${res_ppl_q[$cache_type]:-n/a}"
    pq_u="${res_ppl_q_unc[$cache_type]:-}"
    pb="${res_ppl_base[$cache_type]:-}"
    pq_disp="$pq"
    [ -n "$pq_u" ] && pq_disp="${pq}±${pq_u}"

    if [ -n "$pb" ] && [ -n "$pq" ] && [ "$pq" != "n/a" ]; then
        ratio=$(awk "BEGIN { printf \"%.6f\", $pq / $pb }")
    else
        ratio="n/a"
    fi

    printf "  %-14s %-6s %18s %18s\n" "$cache_type" "$bpw" "$pq_disp" "$ratio"

    if [ -n "${res_ppl_q_a[$cache_type]:-}" ]; then
        pq_a="${res_ppl_q_a[$cache_type]}"
        pq_u_a="${res_ppl_q_unc_a[$cache_type]:-}"
        pq_disp_a="$pq_a"
        [ -n "$pq_u_a" ] && pq_disp_a="${pq_a}±${pq_u_a}"
        if [ -n "$pb" ] && [ "$pq_a" != "n/a" ]; then
            ratio_a=$(awk "BEGIN { printf \"%.6f\", $pq_a / $pb }")
        else
            ratio_a="n/a"
        fi
        printf "  %-14s %-6s %18s %18s\n" "  └ α" "-" "$pq_disp_a" "$ratio_a"
    fi
done

echo ""
echo "  Interpretation:"
echo "    Mean KLD → 0 = identical to f16.  Lower is better."
echo "    Δp RMS   → 0 = no probability shift.  Lower is better."
echo "    Same top → 100% = always same top prediction as f16."
echo "    ln(PPL(Q)/PPL(base)) → 0 = same perplexity.  Positive = worse."
echo "    └ α  = MSE-optimal norm correction for TBQ/PQ types"
echo "=========================================="

# --- Regression check ---

num_failed=0
for cache_type in "${CACHE_TYPES[@]}"; do
    kld="${res_kld_mean[$cache_type]:-}"
    if [ -n "$kld" ]; then
        failed=$(awk "BEGIN { print ($kld > 0.1) ? 1 : 0 }")
        if [ "$failed" = "1" ]; then
            echo "FAILED: $cache_type Mean KLD ${kld} exceeds 0.1 threshold"
            num_failed=$((num_failed + 1))
        fi
    fi
done

echo ""
echo "GPU device: $GPU_DEVICE"
if [ "$num_failed" -eq 0 ]; then
    echo "All checks passed."
else
    echo "$num_failed check(s) failed."
fi
if [ -n "$CSV_FINAL" ]; then
    cp "$CSV_FILE" "$CSV_FINAL"
    rm -f "$CSV_FILE"
    echo "Results saved to: $CSV_FINAL (${#CSV_ROWS[@]} rows)"
    echo "Log saved to:     $LOG_FILE"
fi
